export type ChallengeArenaQuestionSeed = {
  sport: string;
  category: string;
  question: string;
  options: string[];
  correctAnswer: string;
  explanation?: string;
  difficulty: "easy" | "intermediate" | "hard";
  bucket: string;
  checksum: string;
};

export const challengeArenaCapitalCityQuestions: ChallengeArenaQuestionSeed[] = [
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of France?",
    options: ["Paris", "Lyon", "Marseille", "Toulouse"],
    correctAnswer: "Paris",
    explanation: "Paris is the capital and largest city of France.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_001",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Japan?",
    options: ["Tokyo", "Osaka", "Kyoto", "Nagoya"],
    correctAnswer: "Tokyo",
    explanation: "Tokyo is Japan's capital city.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_002",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Canada?",
    options: ["Ottawa", "Toronto", "Vancouver", "Montreal"],
    correctAnswer: "Ottawa",
    explanation: "Ottawa is the federal capital of Canada.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_003",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Australia?",
    options: ["Canberra", "Sydney", "Melbourne", "Perth"],
    correctAnswer: "Canberra",
    explanation: "Canberra is the capital city of Australia.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_004",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Brazil?",
    options: ["Brasilia", "Rio de Janeiro", "Sao Paulo", "Salvador"],
    correctAnswer: "Brasilia",
    explanation: "Brasilia has been Brazil's capital since 1960.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_005",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Egypt?",
    options: ["Cairo", "Alexandria", "Giza", "Luxor"],
    correctAnswer: "Cairo",
    explanation: "Cairo is the capital city of Egypt.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_006",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Kenya?",
    options: ["Nairobi", "Mombasa", "Kisumu", "Nakuru"],
    correctAnswer: "Nairobi",
    explanation: "Nairobi is Kenya's capital city.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_007",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of South Korea?",
    options: ["Seoul", "Busan", "Incheon", "Daegu"],
    correctAnswer: "Seoul",
    explanation: "Seoul is the capital city of South Korea.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_008",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Argentina?",
    options: ["Buenos Aires", "Cordoba", "Rosario", "Mendoza"],
    correctAnswer: "Buenos Aires",
    explanation: "Buenos Aires is the capital city of Argentina.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_009",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of India?",
    options: ["New Delhi", "Mumbai", "Kolkata", "Chennai"],
    correctAnswer: "New Delhi",
    explanation: "New Delhi is the capital of India.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_010",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Germany?",
    options: ["Berlin", "Munich", "Hamburg", "Frankfurt"],
    correctAnswer: "Berlin",
    explanation: "Berlin is the capital city of Germany.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_011",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Italy?",
    options: ["Rome", "Milan", "Naples", "Turin"],
    correctAnswer: "Rome",
    explanation: "Rome is the capital city of Italy.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_012",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Spain?",
    options: ["Madrid", "Barcelona", "Seville", "Valencia"],
    correctAnswer: "Madrid",
    explanation: "Madrid is the capital city of Spain.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_013",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Norway?",
    options: ["Oslo", "Bergen", "Trondheim", "Stavanger"],
    correctAnswer: "Oslo",
    explanation: "Oslo is the capital city of Norway.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_014",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Sweden?",
    options: ["Stockholm", "Gothenburg", "Malmo", "Uppsala"],
    correctAnswer: "Stockholm",
    explanation: "Stockholm is the capital city of Sweden.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_015",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Morocco?",
    options: ["Rabat", "Casablanca", "Marrakesh", "Fez"],
    correctAnswer: "Rabat",
    explanation: "Rabat is the capital city of Morocco.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_016",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the administrative capital of South Africa?",
    options: ["Pretoria", "Cape Town", "Johannesburg", "Durban"],
    correctAnswer: "Pretoria",
    explanation: "Pretoria is South Africa's administrative capital.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_017",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of New Zealand?",
    options: ["Wellington", "Auckland", "Christchurch", "Hamilton"],
    correctAnswer: "Wellington",
    explanation: "Wellington is the capital city of New Zealand.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_018",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Mexico?",
    options: ["Mexico City", "Guadalajara", "Monterrey", "Puebla"],
    correctAnswer: "Mexico City",
    explanation: "Mexico City is the capital of Mexico.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_019",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Turkey?",
    options: ["Ankara", "Istanbul", "Izmir", "Bursa"],
    correctAnswer: "Ankara",
    explanation: "Ankara is the capital city of Turkey.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_020",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Portugal?",
    options: ["Lisbon", "Porto", "Braga", "Coimbra"],
    correctAnswer: "Lisbon",
    explanation: "Lisbon is the capital city of Portugal.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_021",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Greece?",
    options: ["Athens", "Thessaloniki", "Patras", "Heraklion"],
    correctAnswer: "Athens",
    explanation: "Athens is the capital city of Greece.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_022",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Thailand?",
    options: ["Bangkok", "Chiang Mai", "Phuket", "Pattaya"],
    correctAnswer: "Bangkok",
    explanation: "Bangkok is the capital city of Thailand.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_023",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Vietnam?",
    options: ["Hanoi", "Ho Chi Minh City", "Da Nang", "Hue"],
    correctAnswer: "Hanoi",
    explanation: "Hanoi is the capital city of Vietnam.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_024",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Peru?",
    options: ["Lima", "Cusco", "Arequipa", "Trujillo"],
    correctAnswer: "Lima",
    explanation: "Lima is the capital city of Peru.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_025",
  },
];
