import { knowledgeQuestions } from "./knowledgeQuestions";

export type ChallengeArenaQuestionSeed = {
  sport: string;
  category: string;
  question: string;
  options: string[];
  correctAnswer: string;
  acceptedAliases?: string[];
  explanation?: string;
  difficulty: "easy" | "intermediate" | "hard";
  bucket: string;
  checksum: string;
  imageUrl?: string;
  questionKind?: "mcq" | "which_came_first" | "logo_text";
};

const LOGO_ASSET_IDS = {
  "1password": "64d06339c0d057048be1",
  "adidas": "daa374c6ad3431246ef9",
  "airbnb": "fdceafba4642db24dce2",
  "alibabacloud": "4baec41eadb45c6515cf",
  "android": "d7044f3e78c04ad1e70f",
  "anthropic": "e71b0f63f4f0e6ab35cc",
  "apple": "4d3321bc5b5137a4001b",
  "applemusic": "751bb23eecd43abe4cc8",
  "asana": "143785a2ca742b69649a",
  "atlassian": "c2173cbf935747b577a6",
  "audi": "d9688114af906d2d1b4b",
  "behance": "ea58889144c6b2572bde",
  "binance": "628872bac6bf12b73dbc",
  "bitcoin": "4cefcfe45bdee695908a",
  "bitwarden": "8a87d76b9bf1161818d4",
  "bmw": "1744947ab49e99af893f",
  "brave": "cb5dc9051bcfd3d7a2ae",
  "burgerking": "39cda94c350e356f2231",
  "carrefour": "c5ac3f4b7e937d523047",
  "cashapp": "8745a2c5df74816f3857",
  "chase": "910d3908d1fcf5e2c934",
  "chevrolet": "3393b7202b0efe54ff38",
  "citroen": "8f0a66e6b6bc0f53469e",
  "cloudflare": "c59f6267434475b2a988",
  "confluence": "935586951d3c3628b110",
  "databricks": "d391e7773ffc5f90abba",
  "datadog": "a81844fdd4b97d26e4df",
  "debian": "cb557afa2927595fb6b9",
  "deezer": "1eceefa77b87f4624367",
  "deliveroo": "723fca394914b6b28e7c",
  "digitalocean": "621aca640886103db79b",
  "discord": "6f8df7fa19a014849404",
  "docker": "6acbbdd2081885892eca",
  "doordash": "7f745eb3eccb5639a894",
  "dribbble": "10fedc4df4476e770c12",
  "dropbox": "eaf851048adcca38b1bc",
  "duolingo": "aab93f54b7668710a688",
  "elastic": "acb131bae68348fa8694",
  "epicgames": "7cd3879fce5b5ea08ff7",
  "ethereum": "51d4a164dbc53eb7b56c",
  "facebook": "f31e6e47a0a775e0b067",
  "fedora": "493d692ecbb11d8294f9",
  "ferrari": "21cf42d9c50e2552d2eb",
  "figma": "876699a141fd1d5c4659",
  "firefox": "9d009cc507d795751a44",
  "fitbit": "6ca7c60c106223bc707e",
  "flickr": "3f840fdf86a88d85372a",
  "garmin": "38a058df8bd1b262f9b5",
  "github": "a9c6be14ef769f7cc433",
  "gitlab": "b6c5a81b7affb3f0542d",
  "google": "6c0113ec444d8c6e6137",
  "googlechrome": "832b1f84929860dd5f87",
  "grafana": "868951fa21056e62d896",
  "honda": "563a61409bab9abc1d0d",
  "hubspot": "8cfff7d2d8fee8ee285b",
  "huggingface": "6b7a6e2c0278f55f9676",
  "hyundai": "a330cbb5f2e92842a2d3",
  "instagram": "b0ea351c1aad7a38d140",
  "jira": "805a10e9b089a3da33cf",
  "kfc": "27299eb8cc582c77da48",
  "kubernetes": "e61de809bfbf758fe455",
  "lamborghini": "2dc8d950fba6e135ffb3",
  "linux": "9c3671a845b748bb1aa9",
  "mailchimp": "62f12b7ad58e0bdcd615",
  "mapbox": "abb7cc310f103f477983",
  "mastercard": "bd5dfa8ed3fa69e1c104",
  "mazda": "d5842e6fa25e227b8c1f",
  "mcdonalds": "191738d1684401aaded6",
  "medium": "c2f2ec0f7a58eff6905c",
  "meta": "ddc3e3f620263db264f2",
  "mitsubishi": "1e8e19b80cbc8c944137",
  "mongodb": "139b4e2e47b8e4df5438",
  "monster": "d24a5bde7a0971a2fd16",
  "mysql": "039c6ee29993157826ca",
  "netflix": "3f62e64556440721c1b1",
  "netlify": "22299eeb7fb3fa0b0c43",
  "newbalance": "e834420a4e64ab30bc5c",
  "nike": "a817d6cae8134a1963d6",
  "nissan": "b72c96d67bcacb515b7d",
  "notion": "0a108438ec85f535c289",
  "openstreetmap": "e277bc60e32722d7ae05",
  "opera": "9bbd1e835172273f2182",
  "paypal": "de8f284d77e16800d28f",
  "peugeot": "e29d5a597c70e3eb1e32",
  "pinterest": "5b26fca220da13aaf9c9",
  "playstation": "febee3c684739f80eda2",
  "porsche": "1a1adc41f65738bdb95d",
  "postgresql": "ae40b356df9d713e5c6a",
  "prometheus": "63ac5a94315e1dd90779",
  "puma": "a32f2a0e0a838155cfb6",
  "raspberrypi": "13da10bdb766de4fa8e6",
  "redbull": "644dec3616e5cc43aaaa",
  "reddit": "8b4a76e0a4d1a459438c",
  "redhat": "2f350164890e1da0d4d9",
  "redis": "488302522626d8d39516",
  "renault": "6c30518b02a17dde268c",
  "riotgames": "c912b0995b31fea0d816",
  "roblox": "bad2cfb87b9612339042",
  "safari": "92e1fb6cc2a8bc6c93ce",
  "sentry": "4279a0a6ef771ec20ffa",
  "shopee": "b57fe67dab4f0a07c3fa",
  "shopify": "b99e059028f884f6646f",
  "signal": "7c8ea4ed898dea562102",
  "snapchat": "d02926e9f0649aa83f80",
  "snowflake": "a4d2e9ebff689ef89b43",
  "soundcloud": "20c988a269413cd64b61",
  "spotify": "57b8f0848fda6068f754",
  "starbucks": "e1e027c50c4f996d2108",
  "steam": "7a0e00e6f2d533261a72",
  "subaru": "4013a631ef69ad4e6f98",
  "suzuki": "09ee7b1c3ffe4796f6aa",
  "swiggy": "69087b2a6d009fd8640b",
  "tacobell": "43b60d68cf7a30f6421f",
  "target": "a849b85c5f1cc93e611b",
  "telegram": "31cdd9a0aedcdaacd590",
  "tesla": "689635eac40467e312ab",
  "thenorthface": "24ca13e5315c22dbb4e1",
  "tiktok": "414338e23e1902cfc262",
  "tinder": "c0641182e38536792b4b",
  "toyota": "601fd58677a8bf79be23",
  "trello": "4c4518e37b6d8f0f51fd",
  "tripadvisor": "ea69f4f2bbbc9412d940",
  "tumblr": "dd6e55b85a4a153e1e00",
  "twitch": "6931c2696fd04042c0bf",
  "ubuntu": "45962933ce710712843f",
  "underarmour": "3dadfa9c657d64dbb738",
  "unilever": "3590945de9c630ca1cab",
  "unity": "0b7c3bbf086014052267",
  "unrealengine": "86af03eec8b5278812a3",
  "vercel": "ff9c40a0ee803e39fe90",
  "viber": "13eda200616936db8820",
  "vimeo": "072dd6963a685a384291",
  "volkswagen": "041c84918104b8eb9c5a",
  "volvo": "8477775049b02dcbd83b",
  "waze": "36e2663cdc6b2627e8b0",
  "wechat": "417cd69227cd39a7ae0c",
  "whatsapp": "8a18c32d76961ae5c708",
  "wikimediafoundation": "96f1911ea640851c0c48",
  "wikipedia": "afde54f04845779936d5",
  "wordpress": "e3a014d29df709a67247",
  "x": "adab4101508e5d95abce",
  "yelp": "36c46e9dabf82cdb894d",
  "youtube": "7f43a357b2612a0d157d",
  "zoom": "6210c23ce3d47c02978f",
} as const;

function logoAssetUrl(slug: keyof typeof LOGO_ASSET_IDS) {
  return `/arena-logos/opaque/${LOGO_ASSET_IDS[slug]}.svg`;
}


const CAPITAL_CITY_SOURCE = [
  ["Afghanistan", "Kabul"],
  ["Albania", "Tirana"],
  ["Algeria", "Algiers"],
  ["Andorra", "Andorra la Vella"],
  ["Angola", "Luanda"],
  ["Antigua and Barbuda", "Saint John's"],
  ["Argentina", "Buenos Aires"],
  ["Armenia", "Yerevan"],
  ["Australia", "Canberra"],
  ["Austria", "Vienna"],
  ["Azerbaijan", "Baku"],
  ["The Bahamas", "Nassau"],
  ["Bahrain", "Manama"],
  ["Bangladesh", "Dhaka"],
  ["Barbados", "Bridgetown"],
  ["Belarus", "Minsk"],
  ["Belgium", "Brussels"],
  ["Belize", "Belmopan"],
  ["Benin", "Porto-Novo"],
  ["Bhutan", "Thimphu"],
  ["Bolivia", "Sucre"],
  ["Bosnia and Herzegovina", "Sarajevo"],
  ["Botswana", "Gaborone"],
  ["Brazil", "Brasilia"],
  ["Brunei", "Bandar Seri Begawan"],
  ["Bulgaria", "Sofia"],
  ["Burkina Faso", "Ouagadougou"],
  ["Burundi", "Gitega"],
  ["Cape Verde", "Praia"],
  ["Cambodia", "Phnom Penh"],
  ["Cameroon", "Yaounde"],
  ["Canada", "Ottawa"],
  ["Central African Republic", "Bangui"],
  ["Chad", "N'Djamena"],
  ["Chile", "Santiago"],
  ["China", "Beijing"],
  ["Colombia", "Bogota"],
  ["Comoros", "Moroni"],
  ["Republic of the Congo", "Brazzaville"],
  ["Costa Rica", "San Jose"],
  ["Cote d'Ivoire", "Yamoussoukro"],
  ["Croatia", "Zagreb"],
  ["Cuba", "Havana"],
  ["Cyprus", "Nicosia"],
  ["Czechia", "Prague"],
  ["North Korea", "Pyongyang"],
  ["Democratic Republic of the Congo", "Kinshasa"],
  ["Denmark", "Copenhagen"],
  ["Djibouti", "Djibouti"],
  ["Dominica", "Roseau"],
  ["Dominican Republic", "Santo Domingo"],
  ["Ecuador", "Quito"],
  ["Egypt", "Cairo"],
  ["El Salvador", "San Salvador"],
  ["Equatorial Guinea", "Malabo"],
  ["Eritrea", "Asmara"],
  ["Estonia", "Tallinn"],
  ["Eswatini", "Mbabane"],
  ["Ethiopia", "Addis Ababa"],
  ["Fiji", "Suva"],
  ["Finland", "Helsinki"],
  ["France", "Paris"],
  ["Gabon", "Libreville"],
  ["Gambia", "Banjul"],
  ["Georgia", "Tbilisi"],
  ["Germany", "Berlin"],
  ["Ghana", "Accra"],
  ["Greece", "Athens"],
  ["Grenada", "St. George's"],
  ["Guatemala", "Guatemala City"],
  ["Guinea", "Conakry"],
  ["Guinea-Bissau", "Bissau"],
  ["Guyana", "Georgetown"],
  ["Haiti", "Port-au-Prince"],
  ["Honduras", "Tegucigalpa"],
  ["Hungary", "Budapest"],
  ["Iceland", "Reykjavik"],
  ["India", "New Delhi"],
  ["Indonesia", "Jakarta"],
  ["Iran", "Tehran"],
  ["Iraq", "Baghdad"],
  ["Ireland", "Dublin"],
  ["Israel", "Jerusalem"],
  ["Italy", "Rome"],
  ["Jamaica", "Kingston"],
  ["Japan", "Tokyo"],
  ["Jordan", "Amman"],
  ["Kazakhstan", "Astana"],
  ["Kenya", "Nairobi"],
  ["Kiribati", "South Tarawa"],
  ["Kuwait", "Kuwait City"],
  ["Kyrgyzstan", "Bishkek"],
  ["Laos", "Vientiane"],
  ["Latvia", "Riga"],
  ["Lebanon", "Beirut"],
  ["Lesotho", "Maseru"],
  ["Liberia", "Monrovia"],
  ["Libya", "Tripoli"],
  ["Liechtenstein", "Vaduz"],
  ["Lithuania", "Vilnius"],
  ["Luxembourg", "Luxembourg"],
  ["Madagascar", "Antananarivo"],
  ["Malawi", "Lilongwe"],
  ["Malaysia", "Kuala Lumpur"],
  ["Maldives", "Male"],
  ["Mali", "Bamako"],
  ["Malta", "Valletta"],
  ["Marshall Islands", "Majuro"],
  ["Mauritania", "Nouakchott"],
  ["Mauritius", "Port Louis"],
  ["Mexico", "Mexico City"],
  ["Micronesia", "Palikir"],
  ["Monaco", "Monaco"],
  ["Mongolia", "Ulaanbaatar"],
  ["Montenegro", "Podgorica"],
  ["Morocco", "Rabat"],
  ["Mozambique", "Maputo"],
  ["Myanmar", "Naypyidaw"],
  ["Namibia", "Windhoek"],
  ["Nauru", "Yaren"],
  ["Nepal", "Kathmandu"],
  ["Netherlands", "Amsterdam"],
  ["New Zealand", "Wellington"],
  ["Nicaragua", "Managua"],
  ["Niger", "Niamey"],
  ["Nigeria", "Abuja"],
  ["North Macedonia", "Skopje"],
  ["Norway", "Oslo"],
  ["Oman", "Muscat"],
  ["Pakistan", "Islamabad"],
  ["Palau", "Ngerulmud"],
  ["Panama", "Panama City"],
  ["Papua New Guinea", "Port Moresby"],
  ["Paraguay", "Asuncion"],
  ["Peru", "Lima"],
  ["Philippines", "Manila"],
  ["Poland", "Warsaw"],
  ["Portugal", "Lisbon"],
  ["Qatar", "Doha"],
  ["South Korea", "Seoul"],
  ["Moldova", "Chisinau"],
  ["Romania", "Bucharest"],
  ["Russia", "Moscow"],
  ["Rwanda", "Kigali"],
  ["Saint Kitts and Nevis", "Basseterre"],
  ["Saint Lucia", "Castries"],
  ["Saint Vincent and the Grenadines", "Kingstown"],
  ["Samoa", "Apia"],
  ["San Marino", "City of San Marino"],
  ["Sao Tome and Principe", "Sao Tome"],
  ["Saudi Arabia", "Riyadh"],
  ["Senegal", "Dakar"],
  ["Serbia", "Belgrade"],
  ["Seychelles", "Victoria"],
  ["Sierra Leone", "Freetown"],
  ["Singapore", "Singapore"],
  ["Slovakia", "Bratislava"],
  ["Slovenia", "Ljubljana"],
  ["Solomon Islands", "Honiara"],
  ["Somalia", "Mogadishu"],
  ["South Africa", "Pretoria"],
  ["South Sudan", "Juba"],
  ["Spain", "Madrid"],
  ["Sri Lanka", "Sri Jayawardenepura Kotte"],
  ["Sudan", "Khartoum"],
  ["Suriname", "Paramaribo"],
  ["Sweden", "Stockholm"],
  ["Switzerland", "Bern"],
  ["Syria", "Damascus"],
  ["Tajikistan", "Dushanbe"],
  ["Thailand", "Bangkok"],
  ["Timor-Leste", "Dili"],
  ["Togo", "Lome"],
  ["Tonga", "Nuku'alofa"],
  ["Trinidad and Tobago", "Port of Spain"],
  ["Tunisia", "Tunis"],
  ["Turkey", "Ankara"],
  ["Turkmenistan", "Ashgabat"],
  ["Tuvalu", "Funafuti"],
  ["Uganda", "Kampala"],
  ["Ukraine", "Kyiv"],
  ["United Arab Emirates", "Abu Dhabi"],
  ["United Kingdom", "London"],
  ["Tanzania", "Dodoma"],
  ["United States", "Washington, D.C."],
  ["Uruguay", "Montevideo"],
  ["Uzbekistan", "Tashkent"],
  ["Vanuatu", "Port Vila"],
  ["Venezuela", "Caracas"],
  ["Vietnam", "Hanoi"],
  ["Yemen", "Sana'a"],
  ["Zambia", "Lusaka"],
  ["Zimbabwe", "Harare"],
  ["Holy See", "Vatican City"],
  ["State of Palestine", "Ramallah"],
] as const;

const CAPITAL_CITY_OLD_CHECKSUMS: Record<string, string> = {
  "France": "challenge_arena_capitals_v1_001",
  "Japan": "challenge_arena_capitals_v1_002",
  "Canada": "challenge_arena_capitals_v1_003",
  "Australia": "challenge_arena_capitals_v1_004",
  "Brazil": "challenge_arena_capitals_v1_005",
  "Egypt": "challenge_arena_capitals_v1_006",
  "Kenya": "challenge_arena_capitals_v1_007",
  "South Korea": "challenge_arena_capitals_v1_008",
  "Argentina": "challenge_arena_capitals_v1_009",
  "India": "challenge_arena_capitals_v1_010",
  "Germany": "challenge_arena_capitals_v1_011",
  "Italy": "challenge_arena_capitals_v1_012",
  "Spain": "challenge_arena_capitals_v1_013",
  "Norway": "challenge_arena_capitals_v1_014",
  "Sweden": "challenge_arena_capitals_v1_015",
  "Morocco": "challenge_arena_capitals_v1_016",
  "South Africa": "challenge_arena_capitals_v1_017",
  "New Zealand": "challenge_arena_capitals_v1_018",
  "Mexico": "challenge_arena_capitals_v1_019",
  "Turkey": "challenge_arena_capitals_v1_020",
  "Portugal": "challenge_arena_capitals_v1_021",
  "Greece": "challenge_arena_capitals_v1_022",
  "Thailand": "challenge_arena_capitals_v1_023",
  "Vietnam": "challenge_arena_capitals_v1_024",
  "Peru": "challenge_arena_capitals_v1_025",
};

const EASY_CAPITAL_COUNTRIES = new Set([
  "Argentina",
  "Australia",
  "Brazil",
  "Canada",
  "China",
  "Egypt",
  "France",
  "Germany",
  "Greece",
  "India",
  "Ireland",
  "Italy",
  "Japan",
  "Kenya",
  "Mexico",
  "Morocco",
  "Netherlands",
  "New Zealand",
  "Norway",
  "Portugal",
  "Russia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sweden",
  "Thailand",
  "Turkey",
  "United Kingdom",
  "United States",
  "Vietnam",
]);

const HARD_CAPITAL_COUNTRIES = new Set([
  "Andorra",
  "Antigua and Barbuda",
  "Belize",
  "Benin",
  "Bhutan",
  "Brunei",
  "Burkina Faso",
  "Burundi",
  "Cape Verde",
  "Central African Republic",
  "Chad",
  "Comoros",
  "Djibouti",
  "Dominica",
  "Equatorial Guinea",
  "Eritrea",
  "Eswatini",
  "Gambia",
  "Grenada",
  "Guinea-Bissau",
  "Kiribati",
  "Kyrgyzstan",
  "Lesotho",
  "Liechtenstein",
  "Maldives",
  "Marshall Islands",
  "Mauritania",
  "Micronesia",
  "Monaco",
  "Nauru",
  "Palau",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "San Marino",
  "Sao Tome and Principe",
  "Seychelles",
  "Solomon Islands",
  "South Sudan",
  "Tajikistan",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Turkmenistan",
  "Tuvalu",
  "Vanuatu",
  "Holy See",
  "State of Palestine",
]);

const CAPITAL_CITY_SPECIAL_COPY: Record<
  string,
  { question: string; explanation: string }
> = {
  "Bolivia": {
    question: "What is the constitutional capital of Bolivia?",
    explanation: "Sucre is the constitutional capital of Bolivia; La Paz is the seat of government.",
  },
  "Nauru": {
    question: "What district serves as the de facto capital of Nauru?",
    explanation: "Yaren is commonly listed as Nauru's de facto capital district.",
  },
  "South Africa": {
    question: "What is the administrative capital of South Africa?",
    explanation: "Pretoria is South Africa's administrative capital; Cape Town is legislative and Bloemfontein is judicial.",
  },
  "Holy See": {
    question: "What city is the capital of the Holy See?",
    explanation: "Vatican City is the capital and seat of the Holy See.",
  },
  "State of Palestine": {
    question: "Which city is commonly listed as the administrative center of the State of Palestine?",
    explanation: "Ramallah is commonly listed as the administrative center of the State of Palestine.",
  },
};

const CAPITAL_CITY_OPTION_POOL = CAPITAL_CITY_SOURCE.map(([, capital]) => capital);

function normalizeCapitalOption(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]/g, "");
}

function capitalCityOptions(correctAnswer: string, index: number) {
  const options = [correctAnswer];
  let cursor = (index * 17 + 11) % CAPITAL_CITY_OPTION_POOL.length;
  while (options.length < 4) {
    const candidate = CAPITAL_CITY_OPTION_POOL[cursor];
    if (
      !options.some(
        (option) => normalizeCapitalOption(option) === normalizeCapitalOption(candidate),
      )
    ) {
      options.push(candidate);
    }
    cursor = (cursor + 37) % CAPITAL_CITY_OPTION_POOL.length;
  }
  return options;
}

function capitalCityDifficulty(country: string) {
  if (EASY_CAPITAL_COUNTRIES.has(country)) return "easy";
  if (HARD_CAPITAL_COUNTRIES.has(country)) return "hard";
  return "intermediate";
}

function questionCountryName(country: string) {
  return country === "The Bahamas" ? "the Bahamas" : country;
}

function capitalCityChecksum(country: string, index: number) {
  return (
    CAPITAL_CITY_OLD_CHECKSUMS[country] ??
    "challenge_arena_capitals_v2_" + String(index + 1).padStart(3, "0")
  );
}

export const challengeArenaCapitalCityQuestions: ChallengeArenaQuestionSeed[] =
  CAPITAL_CITY_SOURCE.map(([country, capital], index) => {
    const difficulty = capitalCityDifficulty(country);
    const special = CAPITAL_CITY_SPECIAL_COPY[country];
    return {
      sport: "knowledge",
      category: "capital_cities",
      question:
        special?.question ??
        "What is the capital city of " + questionCountryName(country) + "?",
      options: capitalCityOptions(capital, index),
      correctAnswer: capital,
      explanation:
        special?.explanation ??
        capital + " is the capital city of " + questionCountryName(country) + ".",
      difficulty,
      bucket: "knowledge_" + difficulty + "_capital_cities",
      checksum: capitalCityChecksum(country, index),
    };
  });

export const challengeArenaGeneralKnowledgeQuestions: ChallengeArenaQuestionSeed[] =
  knowledgeQuestions
    .filter(
      (question) =>
        question.category !== "which_came_first" &&
        question.category !== "enterprise_logos" &&
        question.category !== "capital_cities",
    )
    .map((question) => ({ ...question }));


// Source SVGs come from Simple Icons; served URLs use opaque copies under
// app/public/arena-logos/opaque so the request path does not reveal the answer.
export const challengeArenaEnterpriseLogoQuestions: ChallengeArenaQuestionSeed[] = [
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Apple",
    acceptedAliases: ["iPhone","Mac"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_001",
    imageUrl: logoAssetUrl("apple"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Google",
    acceptedAliases: ["Alphabet"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_002",
    imageUrl: logoAssetUrl("google"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Meta",
    acceptedAliases: ["Facebook Meta"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_003",
    imageUrl: logoAssetUrl("meta"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Facebook",
    acceptedAliases: ["FB"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_004",
    imageUrl: logoAssetUrl("facebook"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "X",
    acceptedAliases: ["Twitter"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_005",
    imageUrl: logoAssetUrl("x"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Instagram",
    acceptedAliases: ["IG"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_006",
    imageUrl: logoAssetUrl("instagram"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "TikTok",
    acceptedAliases: ["Tik Tok"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_007",
    imageUrl: logoAssetUrl("tiktok"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "YouTube",
    acceptedAliases: ["You Tube"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_008",
    imageUrl: logoAssetUrl("youtube"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Netflix",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_009",
    imageUrl: logoAssetUrl("netflix"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Spotify",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_010",
    imageUrl: logoAssetUrl("spotify"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Snapchat",
    acceptedAliases: ["Snap"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_011",
    imageUrl: logoAssetUrl("snapchat"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Pinterest",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_012",
    imageUrl: logoAssetUrl("pinterest"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Reddit",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_013",
    imageUrl: logoAssetUrl("reddit"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Discord",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_014",
    imageUrl: logoAssetUrl("discord"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Telegram",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_015",
    imageUrl: logoAssetUrl("telegram"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "WhatsApp",
    acceptedAliases: ["Whats App"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_016",
    imageUrl: logoAssetUrl("whatsapp"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Signal",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_017",
    imageUrl: logoAssetUrl("signal"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Zoom",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_018",
    imageUrl: logoAssetUrl("zoom"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Dropbox",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_019",
    imageUrl: logoAssetUrl("dropbox"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Airbnb",
    acceptedAliases: ["Air BnB"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_020",
    imageUrl: logoAssetUrl("airbnb"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Waze",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_021",
    imageUrl: logoAssetUrl("waze"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "DoorDash",
    acceptedAliases: ["Door Dash"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_022",
    imageUrl: logoAssetUrl("doordash"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Deliveroo",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_023",
    imageUrl: logoAssetUrl("deliveroo"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Swiggy",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_024",
    imageUrl: logoAssetUrl("swiggy"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Alibaba Cloud",
    acceptedAliases: ["Alibaba"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_025",
    imageUrl: logoAssetUrl("alibabacloud"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Shopify",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_026",
    imageUrl: logoAssetUrl("shopify"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "PayPal",
    acceptedAliases: ["Pay Pal"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_027",
    imageUrl: logoAssetUrl("paypal"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Mastercard",
    acceptedAliases: ["MasterCard"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_028",
    imageUrl: logoAssetUrl("mastercard"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Cash App",
    acceptedAliases: ["Cashapp"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_029",
    imageUrl: logoAssetUrl("cashapp"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Target",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_030",
    imageUrl: logoAssetUrl("target"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Carrefour",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_031",
    imageUrl: logoAssetUrl("carrefour"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Starbucks",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_032",
    imageUrl: logoAssetUrl("starbucks"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "McDonald's",
    acceptedAliases: ["McDonalds"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_033",
    imageUrl: logoAssetUrl("mcdonalds"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Burger King",
    acceptedAliases: ["BK"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_034",
    imageUrl: logoAssetUrl("burgerking"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "KFC",
    acceptedAliases: ["Kentucky Fried Chicken"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_035",
    imageUrl: logoAssetUrl("kfc"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Taco Bell",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_036",
    imageUrl: logoAssetUrl("tacobell"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Red Bull",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_037",
    imageUrl: logoAssetUrl("redbull"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Monster Energy",
    acceptedAliases: ["Monster"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_038",
    imageUrl: logoAssetUrl("monster"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Nike",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_039",
    imageUrl: logoAssetUrl("nike"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Adidas",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_040",
    imageUrl: logoAssetUrl("adidas"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Puma",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_041",
    imageUrl: logoAssetUrl("puma"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Under Armour",
    acceptedAliases: ["UnderArmor"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_042",
    imageUrl: logoAssetUrl("underarmour"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "New Balance",
    acceptedAliases: ["NB"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_043",
    imageUrl: logoAssetUrl("newbalance"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "The North Face",
    acceptedAliases: ["North Face"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_044",
    imageUrl: logoAssetUrl("thenorthface"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Apple Music",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_045",
    imageUrl: logoAssetUrl("applemusic"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "PlayStation",
    acceptedAliases: ["PS","Sony PlayStation"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_046",
    imageUrl: logoAssetUrl("playstation"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Steam",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_047",
    imageUrl: logoAssetUrl("steam"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Epic Games",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_048",
    imageUrl: logoAssetUrl("epicgames"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Riot Games",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_049",
    imageUrl: logoAssetUrl("riotgames"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Roblox",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_050",
    imageUrl: logoAssetUrl("roblox"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Unity",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_051",
    imageUrl: logoAssetUrl("unity"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Unreal Engine",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_052",
    imageUrl: logoAssetUrl("unrealengine"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "GitHub",
    acceptedAliases: ["Github"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_053",
    imageUrl: logoAssetUrl("github"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "GitLab",
    acceptedAliases: ["Gitlab"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_054",
    imageUrl: logoAssetUrl("gitlab"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Docker",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_055",
    imageUrl: logoAssetUrl("docker"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Kubernetes",
    acceptedAliases: ["K8s"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_056",
    imageUrl: logoAssetUrl("kubernetes"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Linux",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_057",
    imageUrl: logoAssetUrl("linux"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Ubuntu",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_058",
    imageUrl: logoAssetUrl("ubuntu"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Red Hat",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_059",
    imageUrl: logoAssetUrl("redhat"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Fedora",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_060",
    imageUrl: logoAssetUrl("fedora"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Debian",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_061",
    imageUrl: logoAssetUrl("debian"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Android",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_062",
    imageUrl: logoAssetUrl("android"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Google Chrome",
    acceptedAliases: ["Chrome"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_063",
    imageUrl: logoAssetUrl("googlechrome"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Firefox",
    acceptedAliases: ["Mozilla Firefox"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_064",
    imageUrl: logoAssetUrl("firefox"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Safari",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_065",
    imageUrl: logoAssetUrl("safari"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Opera",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_066",
    imageUrl: logoAssetUrl("opera"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Brave",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_067",
    imageUrl: logoAssetUrl("brave"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Cloudflare",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_068",
    imageUrl: logoAssetUrl("cloudflare"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Vercel",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_069",
    imageUrl: logoAssetUrl("vercel"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Netlify",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_070",
    imageUrl: logoAssetUrl("netlify"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "DigitalOcean",
    acceptedAliases: ["Digital Ocean"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_071",
    imageUrl: logoAssetUrl("digitalocean"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "MongoDB",
    acceptedAliases: ["Mongo DB"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_072",
    imageUrl: logoAssetUrl("mongodb"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Redis",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_073",
    imageUrl: logoAssetUrl("redis"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "PostgreSQL",
    acceptedAliases: ["Postgres"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_074",
    imageUrl: logoAssetUrl("postgresql"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "MySQL",
    acceptedAliases: ["My SQL"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_075",
    imageUrl: logoAssetUrl("mysql"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Figma",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_076",
    imageUrl: logoAssetUrl("figma"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Notion",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_077",
    imageUrl: logoAssetUrl("notion"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Trello",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_078",
    imageUrl: logoAssetUrl("trello"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Asana",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_079",
    imageUrl: logoAssetUrl("asana"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Atlassian",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_080",
    imageUrl: logoAssetUrl("atlassian"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Jira",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_081",
    imageUrl: logoAssetUrl("jira"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Confluence",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_082",
    imageUrl: logoAssetUrl("confluence"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Tesla",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_083",
    imageUrl: logoAssetUrl("tesla"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Toyota",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_084",
    imageUrl: logoAssetUrl("toyota"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "BMW",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_085",
    imageUrl: logoAssetUrl("bmw"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Audi",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_086",
    imageUrl: logoAssetUrl("audi"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Volkswagen",
    acceptedAliases: ["VW"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_087",
    imageUrl: logoAssetUrl("volkswagen"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Volvo",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_088",
    imageUrl: logoAssetUrl("volvo"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Ferrari",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_089",
    imageUrl: logoAssetUrl("ferrari"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Lamborghini",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_090",
    imageUrl: logoAssetUrl("lamborghini"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Porsche",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_091",
    imageUrl: logoAssetUrl("porsche"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Honda",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_092",
    imageUrl: logoAssetUrl("honda"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Hyundai",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_093",
    imageUrl: logoAssetUrl("hyundai"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Nissan",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_094",
    imageUrl: logoAssetUrl("nissan"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Renault",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_095",
    imageUrl: logoAssetUrl("renault"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Chevrolet",
    acceptedAliases: ["Chevy"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_096",
    imageUrl: logoAssetUrl("chevrolet"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Citroen",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_097",
    imageUrl: logoAssetUrl("citroen"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Peugeot",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_098",
    imageUrl: logoAssetUrl("peugeot"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Suzuki",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_099",
    imageUrl: logoAssetUrl("suzuki"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Mazda",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_100",
    imageUrl: logoAssetUrl("mazda"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Mitsubishi",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_101",
    imageUrl: logoAssetUrl("mitsubishi"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Subaru",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_102",
    imageUrl: logoAssetUrl("subaru"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Wikipedia",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_103",
    imageUrl: logoAssetUrl("wikipedia"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Tripadvisor",
    acceptedAliases: ["TripAdvisor"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_104",
    imageUrl: logoAssetUrl("tripadvisor"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Yelp",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_105",
    imageUrl: logoAssetUrl("yelp"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Tinder",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_106",
    imageUrl: logoAssetUrl("tinder"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Duolingo",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_107",
    imageUrl: logoAssetUrl("duolingo"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Deezer",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_108",
    imageUrl: logoAssetUrl("deezer"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "SoundCloud",
    acceptedAliases: ["Sound Cloud"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_109",
    imageUrl: logoAssetUrl("soundcloud"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Twitch",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_110",
    imageUrl: logoAssetUrl("twitch"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Vimeo",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_111",
    imageUrl: logoAssetUrl("vimeo"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Flickr",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_112",
    imageUrl: logoAssetUrl("flickr"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Dribbble",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_113",
    imageUrl: logoAssetUrl("dribbble"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Behance",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_114",
    imageUrl: logoAssetUrl("behance"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Medium",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_115",
    imageUrl: logoAssetUrl("medium"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "WordPress",
    acceptedAliases: ["Wordpress"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_116",
    imageUrl: logoAssetUrl("wordpress"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Wikimedia Foundation",
    acceptedAliases: ["Wikimedia"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "hard",
    bucket: "knowledge_hard_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_117",
    imageUrl: logoAssetUrl("wikimediafoundation"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Unilever",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_118",
    imageUrl: logoAssetUrl("unilever"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Raspberry Pi",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_119",
    imageUrl: logoAssetUrl("raspberrypi"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Anthropic",
    acceptedAliases: ["Claude"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_120",
    imageUrl: logoAssetUrl("anthropic"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Hugging Face",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_121",
    imageUrl: logoAssetUrl("huggingface"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Databricks",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_122",
    imageUrl: logoAssetUrl("databricks"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Snowflake",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_123",
    imageUrl: logoAssetUrl("snowflake"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Elastic",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_124",
    imageUrl: logoAssetUrl("elastic"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Grafana",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_125",
    imageUrl: logoAssetUrl("grafana"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Prometheus",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_126",
    imageUrl: logoAssetUrl("prometheus"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "OpenStreetMap",
    acceptedAliases: ["Open Street Map","OSM"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_127",
    imageUrl: logoAssetUrl("openstreetmap"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Mapbox",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_128",
    imageUrl: logoAssetUrl("mapbox"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Garmin",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_129",
    imageUrl: logoAssetUrl("garmin"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Fitbit",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_130",
    imageUrl: logoAssetUrl("fitbit"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Binance",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_131",
    imageUrl: logoAssetUrl("binance"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Bitcoin",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_132",
    imageUrl: logoAssetUrl("bitcoin"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Ethereum",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_133",
    imageUrl: logoAssetUrl("ethereum"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Shopee",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_134",
    imageUrl: logoAssetUrl("shopee"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "WeChat",
    acceptedAliases: ["We Chat"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_135",
    imageUrl: logoAssetUrl("wechat"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Viber",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_136",
    imageUrl: logoAssetUrl("viber"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Tumblr",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_137",
    imageUrl: logoAssetUrl("tumblr"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Chase",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_138",
    imageUrl: logoAssetUrl("chase"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "1Password",
    acceptedAliases: ["One Password"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_139",
    imageUrl: logoAssetUrl("1password"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Bitwarden",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_140",
    imageUrl: logoAssetUrl("bitwarden"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Datadog",
    acceptedAliases: ["Data Dog"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_141",
    imageUrl: logoAssetUrl("datadog"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Sentry",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_142",
    imageUrl: logoAssetUrl("sentry"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Mailchimp",
    acceptedAliases: ["Mail Chimp"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_143",
    imageUrl: logoAssetUrl("mailchimp"),
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "HubSpot",
    acceptedAliases: ["Hub Spot"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_144",
    imageUrl: logoAssetUrl("hubspot"),
    questionKind: "logo_text",
  },
];
