export type ChallengeArenaQuestionSeed = {
  sport: string;
  category: string;
  question: string;
  options: string[];
  correctAnswer: string;
  acceptedAliases?: string[];
  explanation?: string;
  difficulty: "easy" | "intermediate" | "hard";
  bucket: string;
  checksum: string;
  imageUrl?: string;
  questionKind?: "mcq" | "which_came_first" | "logo_text";
};

export const challengeArenaCapitalCityQuestions: ChallengeArenaQuestionSeed[] = [
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of France?",
    options: ["Paris", "Lyon", "Marseille", "Toulouse"],
    correctAnswer: "Paris",
    explanation: "Paris is the capital and largest city of France.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_001",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Japan?",
    options: ["Tokyo", "Osaka", "Kyoto", "Nagoya"],
    correctAnswer: "Tokyo",
    explanation: "Tokyo is Japan's capital city.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_002",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Canada?",
    options: ["Ottawa", "Toronto", "Vancouver", "Montreal"],
    correctAnswer: "Ottawa",
    explanation: "Ottawa is the federal capital of Canada.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_003",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Australia?",
    options: ["Canberra", "Sydney", "Melbourne", "Perth"],
    correctAnswer: "Canberra",
    explanation: "Canberra is the capital city of Australia.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_004",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Brazil?",
    options: ["Brasilia", "Rio de Janeiro", "Sao Paulo", "Salvador"],
    correctAnswer: "Brasilia",
    explanation: "Brasilia has been Brazil's capital since 1960.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_005",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Egypt?",
    options: ["Cairo", "Alexandria", "Giza", "Luxor"],
    correctAnswer: "Cairo",
    explanation: "Cairo is the capital city of Egypt.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_006",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Kenya?",
    options: ["Nairobi", "Mombasa", "Kisumu", "Nakuru"],
    correctAnswer: "Nairobi",
    explanation: "Nairobi is Kenya's capital city.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_007",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of South Korea?",
    options: ["Seoul", "Busan", "Incheon", "Daegu"],
    correctAnswer: "Seoul",
    explanation: "Seoul is the capital city of South Korea.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_008",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Argentina?",
    options: ["Buenos Aires", "Cordoba", "Rosario", "Mendoza"],
    correctAnswer: "Buenos Aires",
    explanation: "Buenos Aires is the capital city of Argentina.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_009",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of India?",
    options: ["New Delhi", "Mumbai", "Kolkata", "Chennai"],
    correctAnswer: "New Delhi",
    explanation: "New Delhi is the capital of India.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_010",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Germany?",
    options: ["Berlin", "Munich", "Hamburg", "Frankfurt"],
    correctAnswer: "Berlin",
    explanation: "Berlin is the capital city of Germany.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_011",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Italy?",
    options: ["Rome", "Milan", "Naples", "Turin"],
    correctAnswer: "Rome",
    explanation: "Rome is the capital city of Italy.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_012",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Spain?",
    options: ["Madrid", "Barcelona", "Seville", "Valencia"],
    correctAnswer: "Madrid",
    explanation: "Madrid is the capital city of Spain.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_013",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Norway?",
    options: ["Oslo", "Bergen", "Trondheim", "Stavanger"],
    correctAnswer: "Oslo",
    explanation: "Oslo is the capital city of Norway.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_014",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Sweden?",
    options: ["Stockholm", "Gothenburg", "Malmo", "Uppsala"],
    correctAnswer: "Stockholm",
    explanation: "Stockholm is the capital city of Sweden.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_015",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Morocco?",
    options: ["Rabat", "Casablanca", "Marrakesh", "Fez"],
    correctAnswer: "Rabat",
    explanation: "Rabat is the capital city of Morocco.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_016",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the administrative capital of South Africa?",
    options: ["Pretoria", "Cape Town", "Johannesburg", "Durban"],
    correctAnswer: "Pretoria",
    explanation: "Pretoria is South Africa's administrative capital.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_017",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of New Zealand?",
    options: ["Wellington", "Auckland", "Christchurch", "Hamilton"],
    correctAnswer: "Wellington",
    explanation: "Wellington is the capital city of New Zealand.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_018",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Mexico?",
    options: ["Mexico City", "Guadalajara", "Monterrey", "Puebla"],
    correctAnswer: "Mexico City",
    explanation: "Mexico City is the capital of Mexico.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_019",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Turkey?",
    options: ["Ankara", "Istanbul", "Izmir", "Bursa"],
    correctAnswer: "Ankara",
    explanation: "Ankara is the capital city of Turkey.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_020",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Portugal?",
    options: ["Lisbon", "Porto", "Braga", "Coimbra"],
    correctAnswer: "Lisbon",
    explanation: "Lisbon is the capital city of Portugal.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_021",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Greece?",
    options: ["Athens", "Thessaloniki", "Patras", "Heraklion"],
    correctAnswer: "Athens",
    explanation: "Athens is the capital city of Greece.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_022",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Thailand?",
    options: ["Bangkok", "Chiang Mai", "Phuket", "Pattaya"],
    correctAnswer: "Bangkok",
    explanation: "Bangkok is the capital city of Thailand.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_023",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Vietnam?",
    options: ["Hanoi", "Ho Chi Minh City", "Da Nang", "Hue"],
    correctAnswer: "Hanoi",
    explanation: "Hanoi is the capital city of Vietnam.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_024",
  },
  {
    sport: "knowledge",
    category: "capital_cities",
    question: "What is the capital city of Peru?",
    options: ["Lima", "Cusco", "Arequipa", "Trujillo"],
    correctAnswer: "Lima",
    explanation: "Lima is the capital city of Peru.",
    difficulty: "easy",
    bucket: "knowledge_easy_capital_cities",
    checksum: "challenge_arena_capitals_v1_025",
  },
];


// SVG assets are bundled under app/public/arena-logos/simple-icons.
export const challengeArenaEnterpriseLogoQuestions: ChallengeArenaQuestionSeed[] = [
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Apple",
    acceptedAliases: ["iPhone","Mac"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_001",
    imageUrl: "/arena-logos/simple-icons/apple.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Google",
    acceptedAliases: ["Alphabet"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_002",
    imageUrl: "/arena-logos/simple-icons/google.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Meta",
    acceptedAliases: ["Facebook Meta"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_003",
    imageUrl: "/arena-logos/simple-icons/meta.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Facebook",
    acceptedAliases: ["FB"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_004",
    imageUrl: "/arena-logos/simple-icons/facebook.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "X",
    acceptedAliases: ["Twitter"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_005",
    imageUrl: "/arena-logos/simple-icons/x.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Instagram",
    acceptedAliases: ["IG"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_006",
    imageUrl: "/arena-logos/simple-icons/instagram.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "TikTok",
    acceptedAliases: ["Tik Tok"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_007",
    imageUrl: "/arena-logos/simple-icons/tiktok.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "YouTube",
    acceptedAliases: ["You Tube"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_008",
    imageUrl: "/arena-logos/simple-icons/youtube.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Netflix",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_009",
    imageUrl: "/arena-logos/simple-icons/netflix.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Spotify",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_010",
    imageUrl: "/arena-logos/simple-icons/spotify.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Snapchat",
    acceptedAliases: ["Snap"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_011",
    imageUrl: "/arena-logos/simple-icons/snapchat.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Pinterest",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_012",
    imageUrl: "/arena-logos/simple-icons/pinterest.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Reddit",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_013",
    imageUrl: "/arena-logos/simple-icons/reddit.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Discord",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_014",
    imageUrl: "/arena-logos/simple-icons/discord.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Telegram",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_015",
    imageUrl: "/arena-logos/simple-icons/telegram.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "WhatsApp",
    acceptedAliases: ["Whats App"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_016",
    imageUrl: "/arena-logos/simple-icons/whatsapp.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Signal",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_017",
    imageUrl: "/arena-logos/simple-icons/signal.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Zoom",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_018",
    imageUrl: "/arena-logos/simple-icons/zoom.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Dropbox",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_019",
    imageUrl: "/arena-logos/simple-icons/dropbox.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Airbnb",
    acceptedAliases: ["Air BnB"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_020",
    imageUrl: "/arena-logos/simple-icons/airbnb.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Waze",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_021",
    imageUrl: "/arena-logos/simple-icons/waze.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "DoorDash",
    acceptedAliases: ["Door Dash"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_022",
    imageUrl: "/arena-logos/simple-icons/doordash.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Deliveroo",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_023",
    imageUrl: "/arena-logos/simple-icons/deliveroo.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Swiggy",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_024",
    imageUrl: "/arena-logos/simple-icons/swiggy.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Alibaba Cloud",
    acceptedAliases: ["Alibaba"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_025",
    imageUrl: "/arena-logos/simple-icons/alibabacloud.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Shopify",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_026",
    imageUrl: "/arena-logos/simple-icons/shopify.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "PayPal",
    acceptedAliases: ["Pay Pal"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_027",
    imageUrl: "/arena-logos/simple-icons/paypal.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Mastercard",
    acceptedAliases: ["MasterCard"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_028",
    imageUrl: "/arena-logos/simple-icons/mastercard.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Cash App",
    acceptedAliases: ["Cashapp"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_029",
    imageUrl: "/arena-logos/simple-icons/cashapp.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Target",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_030",
    imageUrl: "/arena-logos/simple-icons/target.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Carrefour",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_031",
    imageUrl: "/arena-logos/simple-icons/carrefour.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Starbucks",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_032",
    imageUrl: "/arena-logos/simple-icons/starbucks.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "McDonald's",
    acceptedAliases: ["McDonalds"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_033",
    imageUrl: "/arena-logos/simple-icons/mcdonalds.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Burger King",
    acceptedAliases: ["BK"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_034",
    imageUrl: "/arena-logos/simple-icons/burgerking.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "KFC",
    acceptedAliases: ["Kentucky Fried Chicken"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_035",
    imageUrl: "/arena-logos/simple-icons/kfc.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Taco Bell",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_036",
    imageUrl: "/arena-logos/simple-icons/tacobell.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Red Bull",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_037",
    imageUrl: "/arena-logos/simple-icons/redbull.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Monster Energy",
    acceptedAliases: ["Monster"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_038",
    imageUrl: "/arena-logos/simple-icons/monster.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Nike",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_039",
    imageUrl: "/arena-logos/simple-icons/nike.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Adidas",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_040",
    imageUrl: "/arena-logos/simple-icons/adidas.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Puma",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_041",
    imageUrl: "/arena-logos/simple-icons/puma.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Under Armour",
    acceptedAliases: ["UnderArmor"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_042",
    imageUrl: "/arena-logos/simple-icons/underarmour.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "New Balance",
    acceptedAliases: ["NB"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_043",
    imageUrl: "/arena-logos/simple-icons/newbalance.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "The North Face",
    acceptedAliases: ["North Face"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_044",
    imageUrl: "/arena-logos/simple-icons/thenorthface.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Apple Music",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_045",
    imageUrl: "/arena-logos/simple-icons/applemusic.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "PlayStation",
    acceptedAliases: ["PS","Sony PlayStation"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_046",
    imageUrl: "/arena-logos/simple-icons/playstation.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Steam",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_047",
    imageUrl: "/arena-logos/simple-icons/steam.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Epic Games",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_048",
    imageUrl: "/arena-logos/simple-icons/epicgames.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Riot Games",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_049",
    imageUrl: "/arena-logos/simple-icons/riotgames.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Roblox",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_050",
    imageUrl: "/arena-logos/simple-icons/roblox.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Unity",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_051",
    imageUrl: "/arena-logos/simple-icons/unity.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Unreal Engine",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_052",
    imageUrl: "/arena-logos/simple-icons/unrealengine.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "GitHub",
    acceptedAliases: ["Github"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_053",
    imageUrl: "/arena-logos/simple-icons/github.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "GitLab",
    acceptedAliases: ["Gitlab"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_054",
    imageUrl: "/arena-logos/simple-icons/gitlab.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Docker",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_055",
    imageUrl: "/arena-logos/simple-icons/docker.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Kubernetes",
    acceptedAliases: ["K8s"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_056",
    imageUrl: "/arena-logos/simple-icons/kubernetes.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Linux",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_057",
    imageUrl: "/arena-logos/simple-icons/linux.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Ubuntu",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_058",
    imageUrl: "/arena-logos/simple-icons/ubuntu.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Red Hat",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_059",
    imageUrl: "/arena-logos/simple-icons/redhat.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Fedora",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_060",
    imageUrl: "/arena-logos/simple-icons/fedora.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Debian",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_061",
    imageUrl: "/arena-logos/simple-icons/debian.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Android",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_062",
    imageUrl: "/arena-logos/simple-icons/android.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Google Chrome",
    acceptedAliases: ["Chrome"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_063",
    imageUrl: "/arena-logos/simple-icons/googlechrome.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Firefox",
    acceptedAliases: ["Mozilla Firefox"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_064",
    imageUrl: "/arena-logos/simple-icons/firefox.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Safari",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_065",
    imageUrl: "/arena-logos/simple-icons/safari.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Opera",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_066",
    imageUrl: "/arena-logos/simple-icons/opera.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Brave",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_067",
    imageUrl: "/arena-logos/simple-icons/brave.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Cloudflare",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_068",
    imageUrl: "/arena-logos/simple-icons/cloudflare.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Vercel",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_069",
    imageUrl: "/arena-logos/simple-icons/vercel.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Netlify",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_070",
    imageUrl: "/arena-logos/simple-icons/netlify.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "DigitalOcean",
    acceptedAliases: ["Digital Ocean"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_071",
    imageUrl: "/arena-logos/simple-icons/digitalocean.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "MongoDB",
    acceptedAliases: ["Mongo DB"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_072",
    imageUrl: "/arena-logos/simple-icons/mongodb.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Redis",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_073",
    imageUrl: "/arena-logos/simple-icons/redis.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "PostgreSQL",
    acceptedAliases: ["Postgres"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_074",
    imageUrl: "/arena-logos/simple-icons/postgresql.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "MySQL",
    acceptedAliases: ["My SQL"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_075",
    imageUrl: "/arena-logos/simple-icons/mysql.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Figma",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_076",
    imageUrl: "/arena-logos/simple-icons/figma.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Notion",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_077",
    imageUrl: "/arena-logos/simple-icons/notion.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Trello",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_078",
    imageUrl: "/arena-logos/simple-icons/trello.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Asana",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_079",
    imageUrl: "/arena-logos/simple-icons/asana.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Atlassian",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_080",
    imageUrl: "/arena-logos/simple-icons/atlassian.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Jira",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_081",
    imageUrl: "/arena-logos/simple-icons/jira.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Confluence",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_082",
    imageUrl: "/arena-logos/simple-icons/confluence.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Tesla",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_083",
    imageUrl: "/arena-logos/simple-icons/tesla.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Toyota",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_084",
    imageUrl: "/arena-logos/simple-icons/toyota.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "BMW",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_085",
    imageUrl: "/arena-logos/simple-icons/bmw.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Audi",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_086",
    imageUrl: "/arena-logos/simple-icons/audi.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Volkswagen",
    acceptedAliases: ["VW"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_087",
    imageUrl: "/arena-logos/simple-icons/volkswagen.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Volvo",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_088",
    imageUrl: "/arena-logos/simple-icons/volvo.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Ferrari",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_089",
    imageUrl: "/arena-logos/simple-icons/ferrari.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Lamborghini",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_090",
    imageUrl: "/arena-logos/simple-icons/lamborghini.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Porsche",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_091",
    imageUrl: "/arena-logos/simple-icons/porsche.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Honda",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_092",
    imageUrl: "/arena-logos/simple-icons/honda.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Hyundai",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_093",
    imageUrl: "/arena-logos/simple-icons/hyundai.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Nissan",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_094",
    imageUrl: "/arena-logos/simple-icons/nissan.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Renault",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_095",
    imageUrl: "/arena-logos/simple-icons/renault.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Chevrolet",
    acceptedAliases: ["Chevy"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_096",
    imageUrl: "/arena-logos/simple-icons/chevrolet.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Citroen",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_097",
    imageUrl: "/arena-logos/simple-icons/citroen.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Peugeot",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_098",
    imageUrl: "/arena-logos/simple-icons/peugeot.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Suzuki",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_099",
    imageUrl: "/arena-logos/simple-icons/suzuki.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Mazda",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_100",
    imageUrl: "/arena-logos/simple-icons/mazda.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Mitsubishi",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_101",
    imageUrl: "/arena-logos/simple-icons/mitsubishi.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Subaru",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_102",
    imageUrl: "/arena-logos/simple-icons/subaru.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Wikipedia",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_103",
    imageUrl: "/arena-logos/simple-icons/wikipedia.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Tripadvisor",
    acceptedAliases: ["TripAdvisor"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_104",
    imageUrl: "/arena-logos/simple-icons/tripadvisor.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Yelp",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_105",
    imageUrl: "/arena-logos/simple-icons/yelp.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Tinder",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_106",
    imageUrl: "/arena-logos/simple-icons/tinder.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Duolingo",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_107",
    imageUrl: "/arena-logos/simple-icons/duolingo.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Deezer",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_108",
    imageUrl: "/arena-logos/simple-icons/deezer.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "SoundCloud",
    acceptedAliases: ["Sound Cloud"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_109",
    imageUrl: "/arena-logos/simple-icons/soundcloud.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Twitch",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_110",
    imageUrl: "/arena-logos/simple-icons/twitch.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Vimeo",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_111",
    imageUrl: "/arena-logos/simple-icons/vimeo.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Flickr",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_112",
    imageUrl: "/arena-logos/simple-icons/flickr.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Dribbble",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_113",
    imageUrl: "/arena-logos/simple-icons/dribbble.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Behance",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_114",
    imageUrl: "/arena-logos/simple-icons/behance.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Medium",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_115",
    imageUrl: "/arena-logos/simple-icons/medium.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "WordPress",
    acceptedAliases: ["Wordpress"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_116",
    imageUrl: "/arena-logos/simple-icons/wordpress.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Wikimedia Foundation",
    acceptedAliases: ["Wikimedia"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "hard",
    bucket: "knowledge_hard_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_117",
    imageUrl: "/arena-logos/simple-icons/wikimediafoundation.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Unilever",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_118",
    imageUrl: "/arena-logos/simple-icons/unilever.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Raspberry Pi",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_119",
    imageUrl: "/arena-logos/simple-icons/raspberrypi.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Anthropic",
    acceptedAliases: ["Claude"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_120",
    imageUrl: "/arena-logos/simple-icons/anthropic.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Hugging Face",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_121",
    imageUrl: "/arena-logos/simple-icons/huggingface.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Databricks",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_122",
    imageUrl: "/arena-logos/simple-icons/databricks.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Snowflake",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_123",
    imageUrl: "/arena-logos/simple-icons/snowflake.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Elastic",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_124",
    imageUrl: "/arena-logos/simple-icons/elastic.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Grafana",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_125",
    imageUrl: "/arena-logos/simple-icons/grafana.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Prometheus",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_126",
    imageUrl: "/arena-logos/simple-icons/prometheus.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "OpenStreetMap",
    acceptedAliases: ["Open Street Map","OSM"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_127",
    imageUrl: "/arena-logos/simple-icons/openstreetmap.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Mapbox",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_128",
    imageUrl: "/arena-logos/simple-icons/mapbox.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Garmin",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_129",
    imageUrl: "/arena-logos/simple-icons/garmin.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Fitbit",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_130",
    imageUrl: "/arena-logos/simple-icons/fitbit.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Binance",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_131",
    imageUrl: "/arena-logos/simple-icons/binance.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Bitcoin",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_132",
    imageUrl: "/arena-logos/simple-icons/bitcoin.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Ethereum",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "easy",
    bucket: "knowledge_easy_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_133",
    imageUrl: "/arena-logos/simple-icons/ethereum.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Shopee",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_134",
    imageUrl: "/arena-logos/simple-icons/shopee.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "WeChat",
    acceptedAliases: ["We Chat"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_135",
    imageUrl: "/arena-logos/simple-icons/wechat.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Viber",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_136",
    imageUrl: "/arena-logos/simple-icons/viber.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Tumblr",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_137",
    imageUrl: "/arena-logos/simple-icons/tumblr.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Chase",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_138",
    imageUrl: "/arena-logos/simple-icons/chase.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "1Password",
    acceptedAliases: ["One Password"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_139",
    imageUrl: "/arena-logos/simple-icons/1password.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Bitwarden",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_140",
    imageUrl: "/arena-logos/simple-icons/bitwarden.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Datadog",
    acceptedAliases: ["Data Dog"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_141",
    imageUrl: "/arena-logos/simple-icons/datadog.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Sentry",
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_142",
    imageUrl: "/arena-logos/simple-icons/sentry.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "Mailchimp",
    acceptedAliases: ["Mail Chimp"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_143",
    imageUrl: "/arena-logos/simple-icons/mailchimp.svg",
    questionKind: "logo_text",
  },
  {
    sport: "knowledge",
    category: "enterprise_logos",
    question: "Name this company logo.",
    options: [],
    correctAnswer: "HubSpot",
    acceptedAliases: ["Hub Spot"],
    explanation: "Logo SVG bundled from Simple Icons CC0 assets; brand trademarks remain with their owners.",
    difficulty: "intermediate",
    bucket: "knowledge_intermediate_enterprise_logos",
    checksum: "challenge_arena_enterprise_logos_v1_144",
    imageUrl: "/arena-logos/simple-icons/hubspot.svg",
    questionKind: "logo_text",
  },
];
