import type { KnowledgeQuestionSeed } from "./knowledgeQuestions";

type Difficulty = KnowledgeQuestionSeed["difficulty"];

type RawExpansionFact = {
  category: string;
  difficulty: Difficulty;
  question: string;
  correctAnswer: string;
  distractors: [string, string, string];
  explanation: string;
  sourceKey: keyof typeof knowledgeExpansionV1Provenance;
};

export const knowledgeExpansionV1Provenance = {
  science_constants_space:
    "Custom VerveQ-authored prompts verified against NIST/CODATA constants, IUPAC/NIST element tables, and NASA planetary fact sheets.",
  geography_places:
    "Custom VerveQ-authored prompts verified against Wikidata-class structured place facts, UNESCO World Heritage records, and CIA World Factbook country profiles.",
  history_inventions:
    "Custom VerveQ-authored prompts verified against Wikidata-class event/person records, Nobel Prize API records, and museum/standards-office structured timelines.",
  language_arts_culture:
    "Custom VerveQ-authored prompts verified against Wikidata-class work/person records, ISO/Library of Congress language-code data, and institutional collection records.",
  no_open_trivia_corpus:
    "No OpenTDB or CC-BY-SA trivia corpus was ingested; rows are custom-authored from open structured/reference facts.",
} as const;

function rotateOptions(
  correctAnswer: string,
  distractors: [string, string, string],
  index: number,
) {
  const options = [correctAnswer, ...distractors];
  const targetIndex = index % 4;
  const [correct] = options.splice(0, 1);
  options.splice(targetIndex, 0, correct);
  return options;
}

function bucket(category: string, difficulty: Difficulty) {
  return `knowledge_${difficulty}_${category}`;
}

function buildRows(facts: RawExpansionFact[]): KnowledgeQuestionSeed[] {
  return facts.map((fact, index) => ({
    sport: "knowledge",
    category: fact.category,
    question: fact.question,
    options: rotateOptions(fact.correctAnswer, fact.distractors, index),
    correctAnswer: fact.correctAnswer,
    explanation: fact.explanation,
    difficulty: fact.difficulty,
    bucket: bucket(fact.category, fact.difficulty),
    checksum: `knowledge_expansion_v1_${String(index + 1).padStart(3, "0")}`,
  }));
}

const RAW_EXPANSION_FACTS: RawExpansionFact[] = [
  {
    category: "chemistry",
    difficulty: "easy",
    question: "A diamond is almost entirely atoms of which element arranged in a crystal lattice?",
    correctAnswer: "Carbon",
    distractors: ["Silicon", "Calcium", "Sulfur"],
    explanation: "Diamond is a crystalline form of carbon.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "easy",
    question: "Which element is defined by having exactly 8 protons?",
    correctAnswer: "Oxygen",
    distractors: ["Nitrogen", "Fluorine", "Neon"],
    explanation: "Atomic number 8 identifies oxygen.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "easy",
    question: "Table salt gets its metallic half from which element?",
    correctAnswer: "Sodium",
    distractors: ["Potassium", "Calcium", "Magnesium"],
    explanation: "Sodium chloride is made from sodium and chlorine ions.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "easy",
    question: "Which gas gives balloons their safer lift instead of flammable hydrogen?",
    correctAnswer: "Helium",
    distractors: ["Neon", "Argon", "Krypton"],
    explanation: "Helium is a light noble gas and is not flammable.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "easy",
    question: "Which element's symbol is Fe, from the Latin name ferrum?",
    correctAnswer: "Iron",
    distractors: ["Fluorine", "Francium", "Fermium"],
    explanation: "Fe is the chemical symbol for iron.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "easy",
    question: "On a periodic table, Ag stands for which metal?",
    correctAnswer: "Silver",
    distractors: ["Argon", "Gold", "Aluminum"],
    explanation: "Ag is the symbol for silver, from argentum.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "easy",
    question: "Which element is liquid near room temperature and has the symbol Hg?",
    correctAnswer: "Mercury",
    distractors: ["Gallium", "Bromine", "Cesium"],
    explanation: "Mercury is a metal that is liquid near room temperature.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "intermediate",
    question: "Which element is named for the dwarf planet once called the ninth planet?",
    correctAnswer: "Plutonium",
    distractors: ["Neptunium", "Uranium", "Curium"],
    explanation: "Plutonium was named after Pluto, following uranium and neptunium.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "intermediate",
    question: "Which element is named after Marie and Pierre Curie?",
    correctAnswer: "Curium",
    distractors: ["Polonium", "Radium", "Fermium"],
    explanation: "Curium honors Marie and Pierre Curie.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "intermediate",
    question: "Which element's name comes from the Greek word for green?",
    correctAnswer: "Chlorine",
    distractors: ["Chromium", "Copper", "Cobalt"],
    explanation: "Chlorine's name traces to the Greek chloros, meaning greenish-yellow.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "intermediate",
    question: "Which element is the main metal in ordinary brass?",
    correctAnswer: "Copper",
    distractors: ["Iron", "Tin", "Lead"],
    explanation: "Brass is primarily copper alloyed with zinc.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "intermediate",
    question: "Which element is paired with copper to make bronze?",
    correctAnswer: "Tin",
    distractors: ["Zinc", "Nickel", "Chromium"],
    explanation: "Bronze is traditionally an alloy of copper and tin.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "intermediate",
    question: "Which element gives ruby its red color as a trace impurity in corundum?",
    correctAnswer: "Chromium",
    distractors: ["Manganese", "Cobalt", "Nickel"],
    explanation: "Trace chromium in aluminum oxide produces ruby's red color.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "intermediate",
    question: "Which noble gas is used in many bright orange-red advertising signs?",
    correctAnswer: "Neon",
    distractors: ["Argon", "Xenon", "Radon"],
    explanation: "Neon glows red-orange in discharge tubes.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "intermediate",
    question: "Which element's symbol is W, from its older name wolfram?",
    correctAnswer: "Tungsten",
    distractors: ["Tellurium", "Tantalum", "Thulium"],
    explanation: "Tungsten uses the symbol W from wolfram.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "hard",
    question: "Which synthetic element is named after the state that includes Berkeley?",
    correctAnswer: "Californium",
    distractors: ["Berkelium", "Americium", "Lawrencium"],
    explanation: "Californium is named after California.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "hard",
    question: "Which element is named after the Scandinavian goddess Freyja through the mineral vanadinite?",
    correctAnswer: "Vanadium",
    distractors: ["Scandium", "Yttrium", "Holmium"],
    explanation: "Vanadium's name is linked to Vanadis, a name for Freyja.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "hard",
    question: "Which element is named for the asteroid Pallas?",
    correctAnswer: "Palladium",
    distractors: ["Platinum", "Promethium", "Praseodymium"],
    explanation: "Palladium was named after the asteroid Pallas.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "hard",
    question: "Which element is named for the village of Ytterby, Sweden?",
    correctAnswer: "Ytterbium",
    distractors: ["Zirconium", "Hafnium", "Rhenium"],
    explanation: "Ytterbium is one of several elements named from Ytterby.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "hard",
    question: "Which element has atomic number 118?",
    correctAnswer: "Oganesson",
    distractors: ["Tennessine", "Livermorium", "Moscovium"],
    explanation: "Oganesson is element 118 on the periodic table.",
    sourceKey: "science_constants_space",
  },
  {
    category: "laws_of_universe",
    difficulty: "easy",
    question: "Which constant is exactly 299,792,458 meters per second in SI units?",
    correctAnswer: "Speed of light in vacuum",
    distractors: ["Speed of sound in dry air", "Earth escape velocity", "Electron drift speed"],
    explanation: "The SI defines the speed of light in vacuum as exactly 299,792,458 m/s.",
    sourceKey: "science_constants_space",
  },
  {
    category: "laws_of_universe",
    difficulty: "easy",
    question: "Which SI base unit is defined using the fixed value of the elementary charge?",
    correctAnswer: "Ampere",
    distractors: ["Kelvin", "Mole", "Candela"],
    explanation: "The ampere is defined by fixing the elementary charge.",
    sourceKey: "science_constants_space",
  },
  {
    category: "laws_of_universe",
    difficulty: "intermediate",
    question: "The Planck constant is central to which area of physics?",
    correctAnswer: "Quantum mechanics",
    distractors: ["Plate tectonics", "Fluid statics", "Classical taxonomy"],
    explanation: "Planck's constant links photon energy to frequency in quantum physics.",
    sourceKey: "science_constants_space",
  },
  {
    category: "laws_of_universe",
    difficulty: "intermediate",
    question: "Which constant links a gas sample's pressure, volume, amount, and temperature?",
    correctAnswer: "Molar gas constant",
    distractors: ["Faraday constant", "Rydberg constant", "Stefan-Boltzmann constant"],
    explanation: "The ideal gas law uses the molar gas constant R.",
    sourceKey: "science_constants_space",
  },
  {
    category: "laws_of_universe",
    difficulty: "intermediate",
    question: "Which constant is often written as k_B?",
    correctAnswer: "Boltzmann constant",
    distractors: ["Avogadro constant", "Fine-structure constant", "Gravitational constant"],
    explanation: "k_B denotes the Boltzmann constant.",
    sourceKey: "science_constants_space",
  },
  {
    category: "laws_of_universe",
    difficulty: "hard",
    question: "Which dimensionless constant is close to 1/137?",
    correctAnswer: "Fine-structure constant",
    distractors: ["Avogadro constant", "Faraday constant", "Gas constant"],
    explanation: "The fine-structure constant is a dimensionless coupling constant near 1/137.",
    sourceKey: "science_constants_space",
  },
  {
    category: "laws_of_universe",
    difficulty: "hard",
    question: "Which constant gives the electric charge per mole of electrons?",
    correctAnswer: "Faraday constant",
    distractors: ["Planck constant", "Hubble constant", "Rydberg constant"],
    explanation: "The Faraday constant is the charge carried by one mole of electrons.",
    sourceKey: "science_constants_space",
  },
  {
    category: "laws_of_universe",
    difficulty: "hard",
    question: "Which constant appears in the blackbody power law proportional to temperature to the fourth power?",
    correctAnswer: "Stefan-Boltzmann constant",
    distractors: ["Boltzmann constant", "Planck constant", "Coulomb constant"],
    explanation: "The Stefan-Boltzmann constant appears in the Stefan-Boltzmann law.",
    sourceKey: "science_constants_space",
  },
  {
    category: "astronomy",
    difficulty: "easy",
    question: "Which planet has the tallest volcano in the solar system, Olympus Mons?",
    correctAnswer: "Planet Mars",
    distractors: ["Planet Venus", "Planet Mercury", "Planet Earth"],
    explanation: "Olympus Mons is a giant shield volcano on Mars.",
    sourceKey: "science_constants_space",
  },
  {
    category: "astronomy",
    difficulty: "easy",
    question: "Which planet is orbited by the moon Titan?",
    correctAnswer: "Saturn",
    distractors: ["Jupiter", "Uranus", "Neptune"],
    explanation: "Titan is Saturn's largest moon.",
    sourceKey: "science_constants_space",
  },
  {
    category: "astronomy",
    difficulty: "easy",
    question: "Which planet's Great Red Spot is a long-lived storm?",
    correctAnswer: "Planet Jupiter",
    distractors: ["Planet Saturn", "Planet Mars", "Planet Neptune"],
    explanation: "The Great Red Spot is a storm in Jupiter's atmosphere.",
    sourceKey: "science_constants_space",
  },
  {
    category: "astronomy",
    difficulty: "easy",
    question: "Which planet is famous for a runaway greenhouse atmosphere and surface heat?",
    correctAnswer: "Planet Venus",
    distractors: ["Planet Mars", "Planet Mercury", "Planet Uranus"],
    explanation: "Venus has an extremely dense carbon dioxide atmosphere and intense surface heat.",
    sourceKey: "science_constants_space",
  },
  {
    category: "astronomy",
    difficulty: "easy",
    question: "Which dwarf planet is orbited by Charon?",
    correctAnswer: "Pluto",
    distractors: ["Ceres", "Eris", "Haumea"],
    explanation: "Charon is Pluto's largest moon.",
    sourceKey: "science_constants_space",
  },
  {
    category: "astronomy",
    difficulty: "intermediate",
    question: "Which moon has a subsurface ocean and an icy crust crossed by reddish streaks?",
    correctAnswer: "Europa",
    distractors: ["Io", "Callisto", "Ganymede"],
    explanation: "Europa is an icy moon of Jupiter with strong evidence for a subsurface ocean.",
    sourceKey: "science_constants_space",
  },
  {
    category: "astronomy",
    difficulty: "intermediate",
    question: "Which moon is the most volcanically active world in the solar system?",
    correctAnswer: "Io",
    distractors: ["Europa", "Titan", "Triton"],
    explanation: "Io's tidal heating drives intense volcanism.",
    sourceKey: "science_constants_space",
  },
  {
    category: "astronomy",
    difficulty: "intermediate",
    question: "Which planet rotates on its side with an axial tilt near 98 degrees?",
    correctAnswer: "Uranus",
    distractors: ["Neptune", "Saturn", "Jupiter"],
    explanation: "Uranus has an extreme axial tilt and appears to roll around the Sun.",
    sourceKey: "science_constants_space",
  },
  {
    category: "astronomy",
    difficulty: "intermediate",
    question: "Which moon of Neptune orbits backward compared with Neptune's rotation?",
    correctAnswer: "Triton",
    distractors: ["Proteus", "Nereid", "Larissa"],
    explanation: "Triton has a retrograde orbit around Neptune.",
    sourceKey: "science_constants_space",
  },
  {
    category: "astronomy",
    difficulty: "intermediate",
    question: "Which asteroid belt object is also classified as a dwarf planet?",
    correctAnswer: "Ceres",
    distractors: ["Vesta", "Pallas", "Hygiea"],
    explanation: "Ceres is the only dwarf planet in the main asteroid belt.",
    sourceKey: "science_constants_space",
  },
  {
    category: "astronomy",
    difficulty: "hard",
    question: "Which Saturn moon has geysers erupting from its south polar region?",
    correctAnswer: "Enceladus",
    distractors: ["Mimas", "Iapetus", "Rhea"],
    explanation: "Cassini observed plumes erupting from Enceladus.",
    sourceKey: "science_constants_space",
  },
  {
    category: "astronomy",
    difficulty: "hard",
    question: "Which Kuiper belt object is famous for its elongated, ringed shape?",
    correctAnswer: "Haumea",
    distractors: ["Makemake", "Eris", "Ceres"],
    explanation: "Haumea is a rapidly rotating dwarf planet with an elongated shape and a ring.",
    sourceKey: "science_constants_space",
  },
  {
    category: "astronomy",
    difficulty: "hard",
    question: "Which spacecraft was the first to orbit Jupiter?",
    correctAnswer: "NASA Galileo",
    distractors: ["NASA Juno", "NASA Voyager 1", "NASA Pioneer 10"],
    explanation: "NASA's Galileo spacecraft entered orbit around Jupiter in 1995.",
    sourceKey: "science_constants_space",
  },
  {
    category: "astronomy",
    difficulty: "hard",
    question: "Which mission delivered the Huygens probe to Saturn's moon Titan?",
    correctAnswer: "Cassini",
    distractors: ["Galileo", "Voyager 2", "New Horizons"],
    explanation: "The Cassini-Huygens mission carried the Huygens lander to Titan.",
    sourceKey: "science_constants_space",
  },
  {
    category: "astronomy",
    difficulty: "hard",
    question: "Which spacecraft flew past Pluto in 2015?",
    correctAnswer: "New Horizons",
    distractors: ["Dawn", "Rosetta", "MESSENGER"],
    explanation: "NASA's New Horizons spacecraft flew by Pluto in July 2015.",
    sourceKey: "science_constants_space",
  },
  {
    category: "earth_science",
    difficulty: "easy",
    question: "Which layer of Earth is liquid and helps generate the magnetic field?",
    correctAnswer: "Outer core",
    distractors: ["Inner core", "Mantle", "Crust"],
    explanation: "The liquid outer core drives the geodynamo that produces Earth's magnetic field.",
    sourceKey: "science_constants_space",
  },
  {
    category: "earth_science",
    difficulty: "easy",
    question: "Which scale is used for the hardness of minerals?",
    correctAnswer: "Mohs scale",
    distractors: ["Richter scale", "Beaufort scale", "pH scale"],
    explanation: "The Mohs scale ranks minerals by scratch hardness.",
    sourceKey: "science_constants_space",
  },
  {
    category: "earth_science",
    difficulty: "easy",
    question: "Which rock type forms from cooled magma or lava?",
    correctAnswer: "Igneous",
    distractors: ["Sedimentary", "Metamorphic", "Foliated"],
    explanation: "Igneous rocks form when molten rock cools and solidifies.",
    sourceKey: "science_constants_space",
  },
  {
    category: "earth_science",
    difficulty: "intermediate",
    question: "Which ocean current helps keep western Europe milder than similar latitudes in Canada?",
    correctAnswer: "Gulf Stream",
    distractors: ["Humboldt Current", "Kuroshio Current", "Benguela Current"],
    explanation: "The Gulf Stream transports warm water into the North Atlantic.",
    sourceKey: "science_constants_space",
  },
  {
    category: "earth_science",
    difficulty: "intermediate",
    question: "Which boundary type creates new oceanic crust at mid-ocean ridges?",
    correctAnswer: "Divergent boundary",
    distractors: ["Convergent boundary", "Transform boundary", "Subduction zone"],
    explanation: "Divergent boundaries pull plates apart and create new crust.",
    sourceKey: "science_constants_space",
  },
  {
    category: "earth_science",
    difficulty: "intermediate",
    question: "Which greenhouse gas is measured at Mauna Loa in the Keeling Curve?",
    correctAnswer: "Carbon dioxide",
    distractors: ["Methane", "Ozone", "Nitrous oxide"],
    explanation: "The Keeling Curve tracks atmospheric carbon dioxide over time.",
    sourceKey: "science_constants_space",
  },
  {
    category: "earth_science",
    difficulty: "hard",
    question: "Which supercontinent existed before Pangaea in many plate-tectonic reconstructions?",
    correctAnswer: "Rodinia",
    distractors: ["Laurasia", "Gondwana", "Pannotia"],
    explanation: "Rodinia is commonly reconstructed as an older supercontinent before Pangaea.",
    sourceKey: "science_constants_space",
  },
  {
    category: "earth_science",
    difficulty: "hard",
    question: "Which seismic wave type cannot travel through liquids?",
    correctAnswer: "S-waves",
    distractors: ["P-waves", "Rayleigh waves", "Love waves"],
    explanation: "Shear waves, or S-waves, cannot pass through liquid layers.",
    sourceKey: "science_constants_space",
  },
  {
    category: "earth_science",
    difficulty: "hard",
    question: "Which mineral group includes olivine, common in Earth's upper mantle?",
    correctAnswer: "Silicates",
    distractors: ["Carbonates", "Sulfates", "Halides"],
    explanation: "Olivine is a silicate mineral group common in mantle rocks.",
    sourceKey: "science_constants_space",
  },
  {
    category: "biology",
    difficulty: "easy",
    question: "Which molecule is the main energy currency used directly by cells?",
    correctAnswer: "ATP",
    distractors: ["DNA", "RNA", "Hemoglobin"],
    explanation: "ATP stores and transfers energy for cellular work.",
    sourceKey: "science_constants_space",
  },
  {
    category: "biology",
    difficulty: "easy",
    question: "Which organelle is often called the cell's power plant?",
    correctAnswer: "Mitochondrion",
    distractors: ["Ribosome", "Lysosome", "Golgi apparatus"],
    explanation: "Mitochondria generate much of the cell's ATP.",
    sourceKey: "science_constants_space",
  },
  {
    category: "biology",
    difficulty: "easy",
    question: "Which blood cells carry oxygen using hemoglobin?",
    correctAnswer: "Red blood cells",
    distractors: ["Platelets", "White blood cells", "Plasma cells"],
    explanation: "Red blood cells transport oxygen with hemoglobin.",
    sourceKey: "science_constants_space",
  },
  {
    category: "biology",
    difficulty: "intermediate",
    question: "Which process copies DNA into RNA?",
    correctAnswer: "Transcription",
    distractors: ["Translation", "Replication", "Fermentation"],
    explanation: "Transcription uses DNA as a template to make RNA.",
    sourceKey: "science_constants_space",
  },
  {
    category: "biology",
    difficulty: "intermediate",
    question: "Which nitrogen base appears in RNA but not DNA?",
    correctAnswer: "Uracil",
    distractors: ["Thymine", "Adenine", "Guanine"],
    explanation: "RNA uses uracil where DNA uses thymine.",
    sourceKey: "science_constants_space",
  },
  {
    category: "biology",
    difficulty: "intermediate",
    question: "Which symbiotic structure helps many legumes fix nitrogen?",
    correctAnswer: "Root nodules",
    distractors: ["Pollen sacs", "Seed cones", "Guard cells"],
    explanation: "Legume root nodules host nitrogen-fixing bacteria.",
    sourceKey: "science_constants_space",
  },
  {
    category: "biology",
    difficulty: "hard",
    question: "Retroviruses rely on which enzyme to make DNA from an RNA template?",
    correctAnswer: "Reverse transcriptase",
    distractors: ["DNA ligase", "RNA polymerase", "Helicase"],
    explanation: "Retroviruses use reverse transcriptase to make DNA from RNA.",
    sourceKey: "science_constants_space",
  },
  {
    category: "biology",
    difficulty: "hard",
    question: "Which cell structure organizes microtubules during animal-cell division?",
    correctAnswer: "Centrosome",
    distractors: ["Nucleolus", "Peroxisome", "Vacuole"],
    explanation: "The centrosome is a major microtubule-organizing center in animal cells.",
    sourceKey: "science_constants_space",
  },
  {
    category: "biology",
    difficulty: "hard",
    question: "Which pigment-protein complex starts oxygen-producing photosynthesis by splitting water?",
    correctAnswer: "Photosystem II",
    distractors: ["Photosystem I", "RuBisCO", "ATP synthase"],
    explanation: "Photosystem II drives water splitting in oxygenic photosynthesis.",
    sourceKey: "science_constants_space",
  },
  {
    category: "geography",
    difficulty: "easy",
    question: "Which country contains the rock-hewn churches of Lalibela?",
    correctAnswer: "Ethiopia",
    distractors: ["Eritrea", "Sudan", "Kenya"],
    explanation: "The rock-hewn churches of Lalibela are in Ethiopia.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "easy",
    question: "Machu Picchu is located in which country?",
    correctAnswer: "Peru",
    distractors: ["Bolivia", "Ecuador", "Colombia"],
    explanation: "Machu Picchu is an Inca site in Peru.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "easy",
    question: "Angkor Wat is a landmark of which country?",
    correctAnswer: "Cambodia",
    distractors: ["Thailand", "Laos", "Vietnam"],
    explanation: "Angkor Wat is a temple complex in Cambodia.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "easy",
    question: "Which country is home to the Taj Mahal?",
    correctAnswer: "India",
    distractors: ["Pakistan", "Bangladesh", "Nepal"],
    explanation: "The Taj Mahal is in Agra, India.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "easy",
    question: "Which country contains the archaeological site Chichen Itza?",
    correctAnswer: "Mexico",
    distractors: ["Guatemala", "Belize", "Honduras"],
    explanation: "Chichen Itza is a Maya site on Mexico's Yucatan Peninsula.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "easy",
    question: "Which country is famous for the rock-cut churches of Lalibela?",
    correctAnswer: "Ethiopia",
    distractors: ["Eritrea", "Sudan", "Kenya"],
    explanation: "Lalibela's rock-hewn churches are in Ethiopia.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "easy",
    question: "Which country contains the island of Bali?",
    correctAnswer: "Indonesia",
    distractors: ["Malaysia", "Philippines", "Sri Lanka"],
    explanation: "Bali is an island and province of Indonesia.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "easy",
    question: "Which country has the island group called the Galapagos?",
    correctAnswer: "Ecuador",
    distractors: ["Chile", "Peru", "Costa Rica"],
    explanation: "The Galapagos Islands are part of Ecuador.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "intermediate",
    question: "Which country surrounds the tiny state of San Marino?",
    correctAnswer: "Italy",
    distractors: ["France", "Austria", "Slovenia"],
    explanation: "San Marino is an enclave surrounded by Italy.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "intermediate",
    question: "Which country completely surrounds Lesotho?",
    correctAnswer: "South Africa",
    distractors: ["Eswatini", "Botswana", "Mozambique"],
    explanation: "Lesotho is an enclave within South Africa.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "intermediate",
    question: "Which sea lies between Australia and New Zealand?",
    correctAnswer: "Tasman Sea",
    distractors: ["Coral Sea", "Arafura Sea", "Timor Sea"],
    explanation: "The Tasman Sea separates Australia and New Zealand.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "intermediate",
    question: "Which strait connects the Black Sea with the Sea of Marmara?",
    correctAnswer: "Bosporus",
    distractors: ["Dardanelles", "Kerch Strait", "Strait of Messina"],
    explanation: "The Bosporus connects the Black Sea to the Sea of Marmara.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "intermediate",
    question: "Which lake is shared by Tanzania, Uganda, and Kenya?",
    correctAnswer: "Lake Victoria",
    distractors: ["Lake Tanganyika", "Lake Malawi", "Lake Turkana"],
    explanation: "Lake Victoria is bordered by Tanzania, Uganda, and Kenya.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "intermediate",
    question: "Which desert covers much of Botswana?",
    correctAnswer: "Kalahari Desert",
    distractors: ["Namib Desert", "Sahara Desert", "Danakil Desert"],
    explanation: "The Kalahari extends across Botswana and neighboring countries.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "intermediate",
    question: "Which river runs through Baghdad?",
    correctAnswer: "Tigris",
    distractors: ["Euphrates", "Jordan", "Orontes"],
    explanation: "Baghdad sits on the Tigris River.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "intermediate",
    question: "Which mountain range forms much of the border between France and Spain?",
    correctAnswer: "Pyrenees",
    distractors: ["Alps", "Carpathians", "Apennines"],
    explanation: "The Pyrenees run between France and Spain.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "hard",
    question: "Which country has the exclave Nakhchivan?",
    correctAnswer: "Azerbaijan",
    distractors: ["Armenia", "Georgia", "Iran"],
    explanation: "Nakhchivan is an autonomous exclave of Azerbaijan.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "hard",
    question: "Which country administers the Faroe Islands as a self-governing territory?",
    correctAnswer: "Denmark",
    distractors: ["Norway", "Iceland", "Sweden"],
    explanation: "The Faroe Islands are a self-governing part of the Kingdom of Denmark.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "hard",
    question: "Which country contains the Danakil Depression?",
    correctAnswer: "Ethiopia",
    distractors: ["Djibouti", "Eritrea", "Somalia"],
    explanation: "The Danakil Depression lies mainly in northeastern Ethiopia.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "hard",
    question: "Which archipelago includes the island of Socotra?",
    correctAnswer: "Yemen",
    distractors: ["Oman", "Somalia", "Eritrea"],
    explanation: "Socotra is part of Yemen.",
    sourceKey: "geography_places",
  },
  {
    category: "history",
    difficulty: "easy",
    question: "Which event happened in 1066?",
    correctAnswer: "Norman conquest of England",
    distractors: ["Fall of Constantinople", "Signing of Magna Carta", "Spanish Armada"],
    explanation: "The Norman conquest of England began in 1066.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "easy",
    question: "Which wall began coming down in 1989?",
    correctAnswer: "Berlin Wall",
    distractors: ["Hadrian's Wall", "Great Wall of China", "Western Wall"],
    explanation: "The Berlin Wall opened and began being dismantled in 1989.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "easy",
    question: "Which empire was ruled by Mansa Musa?",
    correctAnswer: "Mali Empire",
    distractors: ["Songhai Empire", "Ghana Empire", "Benin Empire"],
    explanation: "Mansa Musa was a ruler of the Mali Empire.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "easy",
    question: "Which city hosted the first modern Olympic Games in 1896?",
    correctAnswer: "Athens",
    distractors: ["Paris", "London", "Rome"],
    explanation: "The 1896 Summer Olympics were held in Athens.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "easy",
    question: "Which civilization used cuneiform writing on clay tablets?",
    correctAnswer: "Sumerian civilization",
    distractors: ["Classic Maya", "Inca Empire", "Norse Vikings"],
    explanation: "Cuneiform emerged in ancient Sumer.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "easy",
    question: "Which voyage first reached the Caribbean for Spain in 1492?",
    correctAnswer: "Columbus's first voyage",
    distractors: ["Magellan's circumnavigation", "Cook's first voyage", "Zheng He's first voyage"],
    explanation: "Columbus's first voyage reached the Caribbean in 1492.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "intermediate",
    question: "Which document was sealed at Runnymede in 1215?",
    correctAnswer: "Magna Carta",
    distractors: ["Domesday Book", "Bill of Rights 1689", "Treaty of Paris"],
    explanation: "Magna Carta was sealed at Runnymede in 1215.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "intermediate",
    question: "Which plague pandemic devastated Europe in the mid-14th century?",
    correctAnswer: "Black Death",
    distractors: ["Antonine Plague", "Justinianic Plague", "Spanish flu"],
    explanation: "The Black Death struck Europe in the 1340s and 1350s.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "intermediate",
    question: "Which empire built Machu Picchu?",
    correctAnswer: "Inca Empire",
    distractors: ["Aztec Empire", "Classic Maya", "Moche culture"],
    explanation: "Machu Picchu was built by the Inca.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "intermediate",
    question: "Which Chinese dynasty is associated with the Terracotta Army?",
    correctAnswer: "Qin dynasty",
    distractors: ["Han dynasty", "Tang dynasty", "Ming dynasty"],
    explanation: "The Terracotta Army guarded the tomb of Qin Shi Huang.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "intermediate",
    question: "Which 1648 settlement is often used as shorthand for modern state sovereignty?",
    correctAnswer: "Peace of Westphalia",
    distractors: ["Treaty of Utrecht", "Congress of Vienna", "Peace of Augsburg"],
    explanation: "The Peace of Westphalia ended major European wars in 1648 and is often linked to state sovereignty.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "intermediate",
    question: "Which event is tied to the date July 20, 1969?",
    correctAnswer: "Apollo 11 Moon landing",
    distractors: ["Sputnik launch", "First Space Shuttle launch", "Vostok 1 flight"],
    explanation: "Apollo 11 landed humans on the Moon on July 20, 1969.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "hard",
    question: "Which battle in 490 BCE became a symbol of Athenian resistance to Persia?",
    correctAnswer: "Battle of Marathon",
    distractors: ["Battle of Thermopylae", "Battle of Salamis", "Battle of Plataea"],
    explanation: "The Battle of Marathon was fought in 490 BCE.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "hard",
    question: "Which medieval ruler was crowned emperor in Rome on Christmas Day 800?",
    correctAnswer: "Charlemagne",
    distractors: ["Otto I", "Frederick Barbarossa", "Charles V"],
    explanation: "Charlemagne was crowned emperor by Pope Leo III in 800.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "hard",
    question: "Which city was renamed Istanbul after the Turkish Republic standardized names?",
    correctAnswer: "Constantinople",
    distractors: ["Antioch", "Smyrna", "Nicaea"],
    explanation: "Constantinople is the historical name of Istanbul.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "hard",
    question: "Which empire's capital was Tenochtitlan?",
    correctAnswer: "Aztec Empire",
    distractors: ["Inca Empire", "Classic Maya", "Toltec state"],
    explanation: "Tenochtitlan was the capital of the Aztec Empire.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "hard",
    question: "Which peace agreement divided much of the Americas between Spain and Portugal?",
    correctAnswer: "Treaty of Tordesillas",
    distractors: ["Treaty of Zaragoza", "Treaty of Utrecht", "Treaty of Paris"],
    explanation: "The 1494 Treaty of Tordesillas divided spheres of influence.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "hard",
    question: "Which revolution began with the storming of the Bastille?",
    correctAnswer: "French Revolution",
    distractors: ["Russian Revolution", "Haitian Revolution", "Glorious Revolution"],
    explanation: "The storming of the Bastille in 1789 is a major symbol of the French Revolution.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "hard",
    question: "Which dynasty built much of the Forbidden City in Beijing?",
    correctAnswer: "Ming dynasty",
    distractors: ["Qing dynasty", "Yuan dynasty", "Song dynasty"],
    explanation: "The Forbidden City was built under the Ming dynasty.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "hard",
    question: "Which code is one of the earliest known written legal codes from Babylon?",
    correctAnswer: "Code of Hammurabi",
    distractors: ["Justinian Code", "Napoleonic Code", "Salic Law"],
    explanation: "The Code of Hammurabi is a Babylonian legal code.",
    sourceKey: "history_inventions",
  },
  {
    category: "inventions",
    difficulty: "easy",
    question: "Which invention is associated with Johannes Gutenberg in 15th-century Europe?",
    correctAnswer: "Movable-type printing press",
    distractors: ["Steam locomotive", "Telegraph", "Phonograph"],
    explanation: "Gutenberg is associated with movable-type printing in Europe.",
    sourceKey: "history_inventions",
  },
  {
    category: "inventions",
    difficulty: "easy",
    question: "Which technology did Alexander Graham Bell patent in 1876?",
    correctAnswer: "Telephone",
    distractors: ["Radio", "Television", "Typewriter"],
    explanation: "Bell received a telephone patent in 1876.",
    sourceKey: "history_inventions",
  },
  {
    category: "inventions",
    difficulty: "easy",
    question: "Which invention is linked to Guglielmo Marconi's early wireless communication work?",
    correctAnswer: "Radio",
    distractors: ["Radar", "Telegraph", "Telephone"],
    explanation: "Marconi helped develop practical radio telegraphy.",
    sourceKey: "history_inventions",
  },
  {
    category: "inventions",
    difficulty: "easy",
    question: "Which household device was patented by Josephine Cochrane?",
    correctAnswer: "Dishwasher",
    distractors: ["Vacuum cleaner", "Electric toaster", "Food processor"],
    explanation: "Josephine Cochrane patented an early successful dishwasher.",
    sourceKey: "history_inventions",
  },
  {
    category: "inventions",
    difficulty: "easy",
    question: "Which safety device is Mary Anderson known for inventing?",
    correctAnswer: "Windshield wiper",
    distractors: ["Seat belt", "Airbag", "Turn signal"],
    explanation: "Mary Anderson patented a windshield cleaning device.",
    sourceKey: "history_inventions",
  },
  {
    category: "inventions",
    difficulty: "intermediate",
    question: "Which data-storage format did IBM introduce in the 1950s with RAMAC?",
    correctAnswer: "Hard disk drive",
    distractors: ["Compact disc", "Flash memory", "Magnetic stripe card"],
    explanation: "IBM's RAMAC system used an early hard disk drive.",
    sourceKey: "history_inventions",
  },
  {
    category: "inventions",
    difficulty: "intermediate",
    question: "Which coding system was designed by Louis Braille?",
    correctAnswer: "Braille",
    distractors: ["Morse code", "ASCII", "Unicode"],
    explanation: "Louis Braille developed the tactile reading and writing system named for him.",
    sourceKey: "history_inventions",
  },
  {
    category: "inventions",
    difficulty: "intermediate",
    question: "Which medical imaging method was discovered by Wilhelm Roentgen?",
    correctAnswer: "X-rays",
    distractors: ["MRI", "Ultrasound", "CT scanning"],
    explanation: "Roentgen discovered X-rays in 1895.",
    sourceKey: "history_inventions",
  },
  {
    category: "inventions",
    difficulty: "intermediate",
    question: "Which textile machine is associated with James Hargreaves?",
    correctAnswer: "Spinning jenny",
    distractors: ["Power loom", "Cotton gin", "Flying shuttle"],
    explanation: "Hargreaves invented the spinning jenny.",
    sourceKey: "history_inventions",
  },
  {
    category: "inventions",
    difficulty: "intermediate",
    question: "Which navigation tool uses a freely suspended magnetic needle?",
    correctAnswer: "Magnetic compass",
    distractors: ["Astrolabe", "Sextant", "Chronometer"],
    explanation: "A magnetic compass aligns with Earth's magnetic field.",
    sourceKey: "history_inventions",
  },
  {
    category: "inventions",
    difficulty: "hard",
    question: "Which early computer is associated with Tommy Flowers and codebreaking at Bletchley Park?",
    correctAnswer: "Colossus",
    distractors: ["ENIAC", "UNIVAC I", "Z3"],
    explanation: "Colossus was built for wartime codebreaking at Bletchley Park.",
    sourceKey: "history_inventions",
  },
  {
    category: "inventions",
    difficulty: "hard",
    question: "Which encryption device was famously used by Nazi Germany?",
    correctAnswer: "Enigma machine",
    distractors: ["Lorenz cipher", "Purple machine", "SIGABA"],
    explanation: "The Enigma machine was widely used by Nazi Germany for encrypted communications.",
    sourceKey: "history_inventions",
  },
  {
    category: "inventions",
    difficulty: "hard",
    question: "Which inventor is associated with the first practical safety elevator?",
    correctAnswer: "Elisha Otis",
    distractors: ["Nikola Tesla", "George Westinghouse", "Eli Whitney"],
    explanation: "Elisha Otis demonstrated a safety elevator brake in the 1850s.",
    sourceKey: "history_inventions",
  },
  {
    category: "inventions",
    difficulty: "hard",
    question: "Which protocol suite underpins most Internet communication?",
    correctAnswer: "TCP/IP",
    distractors: ["HTTP/HTML", "SMTP/IMAP", "USB/HDMI"],
    explanation: "TCP/IP is the foundational Internet protocol suite.",
    sourceKey: "history_inventions",
  },
  {
    category: "inventions",
    difficulty: "hard",
    question: "Which standard made text encoding far more consistent across writing systems?",
    correctAnswer: "Unicode",
    distractors: ["Morse code", "Baudot code", "EBCDIC"],
    explanation: "Unicode assigns code points for characters across many writing systems.",
    sourceKey: "history_inventions",
  },
  {
    category: "language",
    difficulty: "easy",
    question: "Which language uses the two-letter ISO code 'es'?",
    correctAnswer: "Spanish",
    distractors: ["Estonian", "Esperanto", "Swedish"],
    explanation: "ISO 639-1 uses 'es' for Spanish.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "language",
    difficulty: "easy",
    question: "The ISO 639-1 code 'de' points to which language?",
    correctAnswer: "German",
    distractors: ["Danish", "Dutch", "Greek"],
    explanation: "ISO 639-1 uses 'de' for German.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "language",
    difficulty: "easy",
    question: "In ISO 639-1, the code 'ja' labels which language?",
    correctAnswer: "Japanese",
    distractors: ["Javanese", "Jamaican Creole", "Kannada"],
    explanation: "ISO 639-1 uses 'ja' for Japanese.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "language",
    difficulty: "easy",
    question: "Which writing system is used for modern Korean?",
    correctAnswer: "Hangul",
    distractors: ["Hiragana", "Cyrillic", "Devanagari"],
    explanation: "Hangul is the alphabet used for Korean.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "language",
    difficulty: "easy",
    question: "Which alphabet is used for Russian?",
    correctAnswer: "Cyrillic",
    distractors: ["Greek", "Latin", "Arabic"],
    explanation: "Russian is written with the Cyrillic alphabet.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "language",
    difficulty: "intermediate",
    question: "Which language family includes Hindi, Persian, and English?",
    correctAnswer: "Indo-European",
    distractors: ["Sino-Tibetan", "Austronesian", "Afroasiatic"],
    explanation: "Hindi, Persian, and English are Indo-European languages.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "language",
    difficulty: "intermediate",
    question: "Which language family includes Swahili and Zulu?",
    correctAnswer: "Niger-Congo",
    distractors: ["Afroasiatic", "Uralic", "Dravidian"],
    explanation: "Swahili and Zulu are Niger-Congo languages.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "language",
    difficulty: "intermediate",
    question: "Which constructed language was created by L. L. Zamenhof?",
    correctAnswer: "Esperanto",
    distractors: ["Interlingua", "Volapuk", "Klingon"],
    explanation: "Esperanto was created by L. L. Zamenhof.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "language",
    difficulty: "intermediate",
    question: "The Rosetta Stone unlocked which ancient writing system?",
    correctAnswer: "Egyptian hieroglyphs",
    distractors: ["Linear B script", "Cuneiform tablets", "Classic Maya script"],
    explanation: "The Rosetta Stone helped decipher Egyptian hieroglyphs.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "language",
    difficulty: "intermediate",
    question: "Which script is used for Hindi and Sanskrit?",
    correctAnswer: "Devanagari",
    distractors: ["Bengali", "Gurmukhi", "Tamil"],
    explanation: "Devanagari is used for Hindi, Sanskrit, and other languages.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "language",
    difficulty: "hard",
    question: "Which language has ISO 639-1 code 'eu'?",
    correctAnswer: "Basque",
    distractors: ["Breton", "Catalan", "Welsh"],
    explanation: "ISO 639-1 assigns 'eu' to Basque.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "language",
    difficulty: "hard",
    question: "In ISO 639-1, the code 'ga' maps to which language?",
    correctAnswer: "Irish",
    distractors: ["Scottish Gaelic", "Welsh", "Manx"],
    explanation: "ISO 639-1 assigns 'ga' to Irish.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "language",
    difficulty: "hard",
    question: "Which writing system was deciphered by Michael Ventris?",
    correctAnswer: "Linear B",
    distractors: ["Linear A", "Etruscan", "Rongorongo"],
    explanation: "Michael Ventris deciphered Linear B as an early form of Greek.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "language",
    difficulty: "hard",
    question: "Which script is written right-to-left and used for Hebrew?",
    correctAnswer: "Hebrew alphabet",
    distractors: ["Greek alphabet", "Georgian script", "Armenian alphabet"],
    explanation: "Hebrew is written with the right-to-left Hebrew alphabet.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "language",
    difficulty: "hard",
    question: "Which federal working language of Ethiopia is written in the Ge'ez script?",
    correctAnswer: "Amharic",
    distractors: ["Somali", "Oromo", "Afar"],
    explanation: "Amharic is written with the Ethiopic, or Ge'ez, script.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "literature_arts",
    difficulty: "easy",
    question: "Which novel carries the subtitle The Modern Prometheus?",
    correctAnswer: "Frankenstein",
    distractors: ["Dracula", "The Island of Doctor Moreau", "The Invisible Man"],
    explanation: "Mary Shelley's Frankenstein is subtitled The Modern Prometheus.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "literature_arts",
    difficulty: "easy",
    question: "Which artist painted The Starry Night?",
    correctAnswer: "Vincent van Gogh",
    distractors: ["Claude Monet", "Paul Cezanne", "Edvard Munch"],
    explanation: "The Starry Night was painted by Vincent van Gogh.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "literature_arts",
    difficulty: "easy",
    question: "Which composer wrote The Four Seasons?",
    correctAnswer: "Antonio Vivaldi",
    distractors: ["Johann Sebastian Bach", "George Frideric Handel", "Wolfgang Amadeus Mozart"],
    explanation: "The Four Seasons is a set of violin concertos by Vivaldi.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "literature_arts",
    difficulty: "easy",
    question: "Which playwright wrote The Crucible?",
    correctAnswer: "Arthur Miller",
    distractors: ["Tennessee Williams", "Eugene O'Neill", "Samuel Beckett"],
    explanation: "Arthur Miller wrote The Crucible.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "literature_arts",
    difficulty: "easy",
    question: "Which museum is home to the Mona Lisa?",
    correctAnswer: "Louvre Museum",
    distractors: ["Uffizi Gallery", "Prado Museum", "Rijksmuseum"],
    explanation: "The Mona Lisa is displayed at the Louvre in Paris.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "literature_arts",
    difficulty: "intermediate",
    question: "Which Japanese artist created The Great Wave off Kanagawa?",
    correctAnswer: "Hokusai",
    distractors: ["Hiroshige", "Utamaro", "Sharaku"],
    explanation: "The Great Wave off Kanagawa is by Katsushika Hokusai.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "literature_arts",
    difficulty: "intermediate",
    question: "Which novel features the fictional land of Macondo?",
    correctAnswer: "One Hundred Years of Solitude",
    distractors: ["The House of the Spirits", "Pedro Paramo", "The Aleph"],
    explanation: "Macondo is central to One Hundred Years of Solitude.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "literature_arts",
    difficulty: "intermediate",
    question: "Which painter is associated with the Blue Period?",
    correctAnswer: "Pablo Picasso",
    distractors: ["Henri Matisse", "Salvador Dali", "Amedeo Modigliani"],
    explanation: "Picasso's Blue Period lasted in the early 1900s.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "literature_arts",
    difficulty: "intermediate",
    question: "Which composer became deaf later in life but continued composing?",
    correctAnswer: "Ludwig van Beethoven",
    distractors: ["Franz Schubert", "Frederic Chopin", "Johannes Brahms"],
    explanation: "Beethoven continued composing after losing much of his hearing.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "literature_arts",
    difficulty: "intermediate",
    question: "Which epic poem follows Odysseus after the Trojan War?",
    correctAnswer: "The Odyssey",
    distractors: ["The Iliad", "The Aeneid", "Metamorphoses"],
    explanation: "The Odyssey follows Odysseus's long journey home.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "literature_arts",
    difficulty: "hard",
    question: "Which architect designed the Guggenheim Museum Bilbao?",
    correctAnswer: "Frank Gehry",
    distractors: ["Zaha Hadid", "Renzo Piano", "I. M. Pei"],
    explanation: "Frank Gehry designed the Guggenheim Museum Bilbao.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "literature_arts",
    difficulty: "hard",
    question: "Which writer created the detective Hercule Poirot?",
    correctAnswer: "Agatha Christie",
    distractors: ["Dorothy L. Sayers", "Arthur Conan Doyle", "Raymond Chandler"],
    explanation: "Agatha Christie created Hercule Poirot.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "literature_arts",
    difficulty: "hard",
    question: "Which composer wrote the opera The Magic Flute?",
    correctAnswer: "Wolfgang Amadeus Mozart",
    distractors: ["Giuseppe Verdi", "Richard Wagner", "Giacomo Puccini"],
    explanation: "The Magic Flute is an opera by Mozart.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "literature_arts",
    difficulty: "hard",
    question: "Which artist made the readymade sculpture Fountain?",
    correctAnswer: "Duchamp",
    distractors: ["Man Ray", "Mondrian", "Brancusi"],
    explanation: "Fountain is a readymade work by Marcel Duchamp.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "literature_arts",
    difficulty: "hard",
    question: "Which novel is narrated by Scout Finch?",
    correctAnswer: "To Kill a Mockingbird",
    distractors: ["The Catcher in the Rye", "A Tree Grows in Brooklyn", "Their Eyes Were Watching God"],
    explanation: "Scout Finch narrates To Kill a Mockingbird.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "culture",
    difficulty: "easy",
    question: "Which board game features kings, queens, rooks, bishops, knights, and pawns?",
    correctAnswer: "Chess",
    distractors: ["Go", "Backgammon", "Scrabble"],
    explanation: "Chess is played on an 8-by-8 board with 64 squares.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "culture",
    difficulty: "easy",
    question: "Which instrument is central to a flamenco performance?",
    correctAnswer: "Guitar",
    distractors: ["Bagpipe", "Sitar", "Balalaika"],
    explanation: "Flamenco commonly features guitar, song, and dance.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "culture",
    difficulty: "easy",
    question: "Which Japanese performing art uses elaborate masks and slow, stylized movement?",
    correctAnswer: "Noh",
    distractors: ["Kabuki", "Bunraku", "Rakugo"],
    explanation: "Noh is a classical Japanese masked theater form.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "culture",
    difficulty: "easy",
    question: "Which cuisine is most associated with kimchi?",
    correctAnswer: "Korean",
    distractors: ["Thai", "Japanese", "Vietnamese"],
    explanation: "Kimchi is a staple of Korean cuisine.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "culture",
    difficulty: "easy",
    question: "Which festival is known as the Hindu festival of lights?",
    correctAnswer: "Diwali",
    distractors: ["Holi", "Navratri", "Vesak"],
    explanation: "Diwali is widely known as the festival of lights.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "culture",
    difficulty: "intermediate",
    question: "Which game uses black and white stones on a grid of intersecting lines?",
    correctAnswer: "Go",
    distractors: ["Shogi", "Mahjong", "Xiangqi"],
    explanation: "Go is played by placing black and white stones on a grid.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "culture",
    difficulty: "intermediate",
    question: "Which martial art's name can be translated as the gentle way?",
    correctAnswer: "Judo",
    distractors: ["Karate", "Aikido", "Taekwondo"],
    explanation: "Judo is commonly translated as the gentle way.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "culture",
    difficulty: "intermediate",
    question: "Which ceremonial tea tradition is closely associated with Japan?",
    correctAnswer: "Chanoyu",
    distractors: ["Yum cha", "Mate circle", "Samovar service"],
    explanation: "Chanoyu refers to the Japanese tea ceremony.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "culture",
    difficulty: "intermediate",
    question: "Which fabric pattern name comes from a Scottish district and is linked to clans?",
    correctAnswer: "Tartan",
    distractors: ["Paisley", "Houndstooth", "Damask"],
    explanation: "Tartan patterns are strongly associated with Scottish clans.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "culture",
    difficulty: "intermediate",
    question: "Which calendar is the basis of the internationally used civil calendar?",
    correctAnswer: "Gregorian calendar",
    distractors: ["Revised Julian calendar", "Hebrew calendar", "Islamic calendar"],
    explanation: "The Gregorian calendar is the most widely used civil calendar.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "culture",
    difficulty: "hard",
    question: "Which ancient board game was found in royal tombs at Ur?",
    correctAnswer: "Royal Game of Ur",
    distractors: ["Senet", "Nine men's morris", "Hnefatafl"],
    explanation: "The Royal Game of Ur is known from ancient Mesopotamian boards.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "culture",
    difficulty: "hard",
    question: "Which theater form features puppeteers visible on stage in black clothing?",
    correctAnswer: "Bunraku",
    distractors: ["Noh", "Kabuki", "Wayang kulit"],
    explanation: "Bunraku is Japanese puppet theater with visible puppeteers.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "culture",
    difficulty: "hard",
    question: "Which Indonesian shadow-puppet tradition uses flat leather figures?",
    correctAnswer: "Wayang kulit",
    distractors: ["Bunraku", "Kathakali", "Commedia dell'arte"],
    explanation: "Wayang kulit is a shadow-puppet theater tradition.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "culture",
    difficulty: "hard",
    question: "Which Andean instrument is a panpipe made from multiple tubes?",
    correctAnswer: "Siku",
    distractors: ["Charango", "Quena", "Bombo"],
    explanation: "The siku is an Andean panpipe.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "culture",
    difficulty: "hard",
    question: "Which Moroccan city is famous for its blue-painted medina?",
    correctAnswer: "Chefchaouen",
    distractors: ["Essaouira", "Meknes", "Tetouan"],
    explanation: "Chefchaouen is known for blue-painted streets and buildings.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "fun_facts",
    difficulty: "easy",
    question: "Which animal's fingerprints are so human-like that they can confuse crime-scene analysis?",
    correctAnswer: "Koala",
    distractors: ["Panda", "Sloth", "Lemur"],
    explanation: "Koalas have fingerprints with patterns similar to human fingerprints.",
    sourceKey: "geography_places",
  },
  {
    category: "fun_facts",
    difficulty: "easy",
    question: "Which bird can hover in place by rapidly beating its wings?",
    correctAnswer: "Hummingbird",
    distractors: ["Swift", "Kingfisher", "Finch"],
    explanation: "Hummingbirds can hover while feeding from flowers.",
    sourceKey: "geography_places",
  },
  {
    category: "fun_facts",
    difficulty: "easy",
    question: "Which mammal lays eggs and has a duck-like bill?",
    correctAnswer: "Platypus",
    distractors: ["Echidna", "Otter", "Beaver"],
    explanation: "The platypus is an egg-laying monotreme with a bill.",
    sourceKey: "geography_places",
  },
  {
    category: "fun_facts",
    difficulty: "easy",
    question: "Which ocean animal has three hearts and blue copper-rich blood?",
    correctAnswer: "Common octopus",
    distractors: ["Giant squid", "Common cuttlefish", "Chambered nautilus"],
    explanation: "Octopuses have three hearts and hemocyanin-based blue blood.",
    sourceKey: "geography_places",
  },
  {
    category: "fun_facts",
    difficulty: "easy",
    question: "Which planet has a day longer than its year?",
    correctAnswer: "Planet Venus",
    distractors: ["Planet Mercury", "Planet Mars", "Planet Neptune"],
    explanation: "Venus rotates very slowly, making its day longer than its orbital year.",
    sourceKey: "science_constants_space",
  },
  {
    category: "fun_facts",
    difficulty: "intermediate",
    question: "Which metal melts in your hand because its melting point is just above room temperature?",
    correctAnswer: "Gallium",
    distractors: ["Bismuth", "Indium", "Tin"],
    explanation: "Gallium melts at about 29.8 degrees Celsius.",
    sourceKey: "science_constants_space",
  },
  {
    category: "fun_facts",
    difficulty: "intermediate",
    question: "Which fruit is botanically a berry but a strawberry is not?",
    correctAnswer: "Banana",
    distractors: ["Apple", "Peach", "Cherry"],
    explanation: "In botanical terms, bananas are berries while strawberries are aggregate accessory fruits.",
    sourceKey: "science_constants_space",
  },
  {
    category: "fun_facts",
    difficulty: "intermediate",
    question: "Which animal can regenerate lost arms and sometimes much of its central disc?",
    correctAnswer: "Sea star",
    distractors: ["Sea urchin", "Sand dollar", "Sea cucumber"],
    explanation: "Many sea stars can regenerate arms, and some can regrow more extensive body parts.",
    sourceKey: "science_constants_space",
  },
  {
    category: "fun_facts",
    difficulty: "intermediate",
    question: "Which spice comes from the dried stigmas of Crocus flowers?",
    correctAnswer: "Saffron",
    distractors: ["Turmeric", "Paprika", "Cardamom"],
    explanation: "Saffron is harvested from Crocus flower stigmas.",
    sourceKey: "geography_places",
  },
  {
    category: "fun_facts",
    difficulty: "intermediate",
    question: "Which island country is known for the extinct dodo bird?",
    correctAnswer: "Mauritius",
    distractors: ["Madagascar", "Seychelles", "Comoros"],
    explanation: "The dodo lived on Mauritius before it went extinct.",
    sourceKey: "geography_places",
  },
  {
    category: "fun_facts",
    difficulty: "hard",
    question: "Which animal has a cube-shaped dropping that helps it mark territory?",
    correctAnswer: "Wombat",
    distractors: ["Capybara", "Tapir", "Alpine marmot"],
    explanation: "Wombats are known for cube-shaped feces.",
    sourceKey: "geography_places",
  },
  {
    category: "fun_facts",
    difficulty: "hard",
    question: "Which fish can produce a powerful electric shock for hunting and defense?",
    correctAnswer: "Electric eel",
    distractors: ["Moray eel", "Lionfish", "Archerfish"],
    explanation: "Electric eels generate strong electric discharges.",
    sourceKey: "science_constants_space",
  },
  {
    category: "fun_facts",
    difficulty: "hard",
    question: "Which mammal is famous for using echolocation while flying at night?",
    correctAnswer: "Bat",
    distractors: ["Flying squirrel", "Sugar glider", "Colugo"],
    explanation: "Many bats navigate and hunt with echolocation.",
    sourceKey: "science_constants_space",
  },
  {
    category: "fun_facts",
    difficulty: "hard",
    question: "Which nickname is commonly used for tardigrades, famous for surviving extreme conditions?",
    correctAnswer: "Water bears",
    distractors: ["Sea monkeys", "Springtails", "Dust mites"],
    explanation: "Tardigrades are commonly nicknamed water bears.",
    sourceKey: "science_constants_space",
  },
  {
    category: "fun_facts",
    difficulty: "hard",
    question: "Which natural glass forms when lava cools too quickly for crystals to grow?",
    correctAnswer: "Obsidian",
    distractors: ["Pumice", "Basalt", "Granite"],
    explanation: "Obsidian is volcanic glass formed by rapid cooling.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "easy",
    question: "Which element is the lightest one on the periodic table?",
    correctAnswer: "Hydrogen",
    distractors: ["Helium", "Lithium", "Beryllium"],
    explanation: "Hydrogen has atomic number 1 and is the lightest element.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "easy",
    question: "Which element is the main reactive ingredient in household bleach compounds?",
    correctAnswer: "Chlorine",
    distractors: ["Bromine", "Iodine", "Fluorine"],
    explanation: "Common chlorine compounds such as sodium hypochlorite are used in bleach.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "intermediate",
    question: "Which element is named after the continent of Europe?",
    correctAnswer: "Europium",
    distractors: ["Erbium", "Einsteinium", "Fermium"],
    explanation: "Europium is named for Europe.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "intermediate",
    question: "Which element has the symbol Pb, from the Latin word plumbum?",
    correctAnswer: "Lead",
    distractors: ["Tin", "Bismuth", "Antimony"],
    explanation: "Lead's symbol Pb comes from plumbum.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "intermediate",
    question: "Which gas was first isolated from the Sun's spectrum before it was found on Earth?",
    correctAnswer: "Helium",
    distractors: ["Neon", "Argon", "Xenon"],
    explanation: "Helium was identified in solar spectral lines before terrestrial samples were confirmed.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "hard",
    question: "Which element was named after Dmitri Mendeleev?",
    correctAnswer: "Mendelevium",
    distractors: ["Nobelium", "Rutherfordium", "Seaborgium"],
    explanation: "Mendelevium honors periodic-table pioneer Dmitri Mendeleev.",
    sourceKey: "science_constants_space",
  },
  {
    category: "chemistry",
    difficulty: "hard",
    question: "Which element sits above iodine in the halogen column?",
    correctAnswer: "Bromine",
    distractors: ["Astatine", "Tellurium", "Selenium"],
    explanation: "The halogen column runs fluorine, chlorine, bromine, iodine, astatine, and tennessine.",
    sourceKey: "science_constants_space",
  },
  {
    category: "laws_of_universe",
    difficulty: "easy",
    question: "Which SI base unit measures thermodynamic temperature?",
    correctAnswer: "Kelvin",
    distractors: ["Pascal", "Candela", "Joule"],
    explanation: "The kelvin is the SI base unit for thermodynamic temperature.",
    sourceKey: "science_constants_space",
  },
  {
    category: "laws_of_universe",
    difficulty: "easy",
    question: "Which force keeps a satellite falling around Earth instead of flying away?",
    correctAnswer: "Gravity",
    distractors: ["Friction", "Buoyancy", "Tension"],
    explanation: "Gravity supplies the centripetal pull for orbital motion.",
    sourceKey: "science_constants_space",
  },
  {
    category: "laws_of_universe",
    difficulty: "intermediate",
    question: "Which constant gives the speed of light in a vacuum exactly?",
    correctAnswer: "299,792,458 m/s",
    distractors: ["300,000,000 m/s", "186,282 m/s", "343 m/s"],
    explanation: "The SI metre is defined using the exact vacuum speed of light, 299,792,458 metres per second.",
    sourceKey: "science_constants_space",
  },
  {
    category: "laws_of_universe",
    difficulty: "intermediate",
    question: "Which law says every action has an equal and opposite reaction?",
    correctAnswer: "Newton's third law",
    distractors: ["Newton's first law", "Newton's second law", "Hooke's law"],
    explanation: "Newton's third law describes paired forces between interacting bodies.",
    sourceKey: "science_constants_space",
  },
  {
    category: "laws_of_universe",
    difficulty: "intermediate",
    question: "Which equation links energy and mass with the speed of light squared?",
    correctAnswer: "E = mc^2",
    distractors: ["F = ma", "p = mv", "V = IR"],
    explanation: "Einstein's mass-energy equivalence is E = mc^2.",
    sourceKey: "science_constants_space",
  },
  {
    category: "laws_of_universe",
    difficulty: "hard",
    question: "Which constant is approximately 6.62607015 x 10^-34 joule seconds?",
    correctAnswer: "Planck constant",
    distractors: ["Boltzmann constant", "Avogadro constant", "Gravitational constant"],
    explanation: "The Planck constant has the exact SI value 6.62607015 x 10^-34 joule seconds.",
    sourceKey: "science_constants_space",
  },
  {
    category: "laws_of_universe",
    difficulty: "hard",
    question: "Which principle says no two electrons in an atom can share every quantum number?",
    correctAnswer: "Pauli exclusion principle",
    distractors: ["Uncertainty principle", "Correspondence principle", "Equivalence principle"],
    explanation: "The Pauli exclusion principle forbids identical fermions from occupying the same quantum state.",
    sourceKey: "science_constants_space",
  },
  {
    category: "astronomy",
    difficulty: "easy",
    question: "Which planet has the moons Phobos and Deimos?",
    correctAnswer: "Planet Mars",
    distractors: ["Planet Venus", "Planet Mercury", "Planet Neptune"],
    explanation: "Mars has two small moons, Phobos and Deimos.",
    sourceKey: "science_constants_space",
  },
  {
    category: "astronomy",
    difficulty: "easy",
    question: "Which moon has a thick nitrogen-rich atmosphere and methane lakes?",
    correctAnswer: "Titan",
    distractors: ["Europa", "Io", "Callisto"],
    explanation: "Saturn's moon Titan has a dense atmosphere and hydrocarbon lakes.",
    sourceKey: "science_constants_space",
  },
  {
    category: "astronomy",
    difficulty: "intermediate",
    question: "Which dwarf planet is the largest object in the asteroid belt?",
    correctAnswer: "Ceres",
    distractors: ["Vesta", "Pallas", "Hygiea"],
    explanation: "Ceres is the largest object in the main asteroid belt and is classified as a dwarf planet.",
    sourceKey: "science_constants_space",
  },
  {
    category: "astronomy",
    difficulty: "intermediate",
    question: "Which Saturn moon sprays water-rich plumes from its south pole?",
    correctAnswer: "Enceladus",
    distractors: ["Titan", "Rhea", "Iapetus"],
    explanation: "Cassini observed water-rich plumes erupting from Enceladus's south polar region.",
    sourceKey: "science_constants_space",
  },
  {
    category: "astronomy",
    difficulty: "intermediate",
    question: "Which planet is known for the fastest measured winds in the Solar System?",
    correctAnswer: "Neptune",
    distractors: ["Uranus", "Saturn", "Jupiter"],
    explanation: "Neptune is known for extremely fast winds measured by spacecraft observations.",
    sourceKey: "science_constants_space",
  },
  {
    category: "astronomy",
    difficulty: "hard",
    question: "Which Neptune moon follows a retrograde orbit and is likely a captured Kuiper Belt object?",
    correctAnswer: "Triton",
    distractors: ["Proteus", "Nereid", "Larissa"],
    explanation: "Triton orbits Neptune backward relative to the planet's rotation, suggesting capture.",
    sourceKey: "science_constants_space",
  },
  {
    category: "astronomy",
    difficulty: "hard",
    question: "Which spacecraft first visited Pluto in 2015?",
    correctAnswer: "New Horizons",
    distractors: ["Voyager 2", "Cassini", "Dawn"],
    explanation: "NASA's New Horizons spacecraft flew past Pluto in July 2015.",
    sourceKey: "science_constants_space",
  },
  {
    category: "earth_science",
    difficulty: "easy",
    question: "Which layer of Earth lies between the crust and the core?",
    correctAnswer: "Mantle",
    distractors: ["Troposphere", "Hydrosphere", "Lithosphere"],
    explanation: "Earth's mantle sits below the crust and above the outer core.",
    sourceKey: "science_constants_space",
  },
  {
    category: "earth_science",
    difficulty: "easy",
    question: "Which cloud type is most associated with thunderstorms?",
    correctAnswer: "Cumulonimbus",
    distractors: ["Cirrus", "Stratus", "Altostratus"],
    explanation: "Cumulonimbus clouds can produce thunderstorms and heavy rain.",
    sourceKey: "science_constants_space",
  },
  {
    category: "earth_science",
    difficulty: "intermediate",
    question: "Which ocean current is also known as the Japan Current?",
    correctAnswer: "Kuroshio Current",
    distractors: ["Gulf Stream", "Benguela Current", "Humboldt Current"],
    explanation: "The Kuroshio Current is often called the Japan Current.",
    sourceKey: "science_constants_space",
  },
  {
    category: "earth_science",
    difficulty: "intermediate",
    question: "Which scale measures earthquake magnitude with moment release rather than local shaking alone?",
    correctAnswer: "Moment magnitude scale",
    distractors: ["Beaufort scale", "Fujita scale", "Saffir-Simpson scale"],
    explanation: "The moment magnitude scale is the modern standard for earthquake magnitude.",
    sourceKey: "science_constants_space",
  },
  {
    category: "earth_science",
    difficulty: "intermediate",
    question: "Which mineral is the hardest reference point on the Mohs scale?",
    correctAnswer: "Diamond",
    distractors: ["Quartz", "Corundum", "Topaz"],
    explanation: "Diamond is rated 10 on the Mohs hardness scale.",
    sourceKey: "science_constants_space",
  },
  {
    category: "earth_science",
    difficulty: "hard",
    question: "Which boundary type is associated with the San Andreas Fault?",
    correctAnswer: "Transform boundary",
    distractors: ["Divergent boundary", "Convergent boundary", "Passive margin"],
    explanation: "The San Andreas Fault marks a transform boundary between tectonic plates.",
    sourceKey: "science_constants_space",
  },
  {
    category: "earth_science",
    difficulty: "hard",
    question: "Which rock texture records gas bubbles trapped in rapidly cooling lava?",
    correctAnswer: "Vesicular",
    distractors: ["Foliated", "Porphyritic", "Clastic"],
    explanation: "Vesicular rocks contain cavities left by gas bubbles.",
    sourceKey: "science_constants_space",
  },
  {
    category: "biology",
    difficulty: "easy",
    question: "Which cell structure contains most of a human cell's DNA?",
    correctAnswer: "Nucleus",
    distractors: ["Ribosome", "Lysosome", "Golgi apparatus"],
    explanation: "Most human cellular DNA is housed in the nucleus.",
    sourceKey: "science_constants_space",
  },
  {
    category: "biology",
    difficulty: "easy",
    question: "Which blood cells are specialized for carrying oxygen?",
    correctAnswer: "Red blood cells",
    distractors: ["Platelets", "T cells", "B cells"],
    explanation: "Red blood cells carry oxygen using hemoglobin.",
    sourceKey: "science_constants_space",
  },
  {
    category: "biology",
    difficulty: "intermediate",
    question: "Which organelle is often called the cell's protein factory?",
    correctAnswer: "Ribosome",
    distractors: ["Mitochondrion", "Peroxisome", "Centrosome"],
    explanation: "Ribosomes translate RNA instructions into proteins.",
    sourceKey: "science_constants_space",
  },
  {
    category: "biology",
    difficulty: "intermediate",
    question: "Which molecule stores genetic information in most living organisms?",
    correctAnswer: "DNA",
    distractors: ["ATP", "RNA", "NADH"],
    explanation: "DNA is the primary hereditary material for most organisms.",
    sourceKey: "science_constants_space",
  },
  {
    category: "biology",
    difficulty: "intermediate",
    question: "Which animal group includes frogs, salamanders, and caecilians?",
    correctAnswer: "Amphibians",
    distractors: ["Reptiles", "Mammals", "Arachnids"],
    explanation: "Frogs, salamanders, and caecilians are amphibians.",
    sourceKey: "science_constants_space",
  },
  {
    category: "biology",
    difficulty: "hard",
    question: "Which enzyme copies DNA into RNA during transcription?",
    correctAnswer: "RNA polymerase",
    distractors: ["DNA ligase", "Helicase", "Reverse transcriptase"],
    explanation: "RNA polymerase synthesizes RNA from a DNA template.",
    sourceKey: "science_constants_space",
  },
  {
    category: "biology",
    difficulty: "hard",
    question: "Which evolutionary term describes similar traits arising independently in unrelated lineages?",
    correctAnswer: "Convergent evolution",
    distractors: ["Genetic drift", "Founder effect", "Artificial selection"],
    explanation: "Convergent evolution produces similar adaptations in distantly related groups.",
    sourceKey: "science_constants_space",
  },
  {
    category: "geography",
    difficulty: "easy",
    question: "Which country contains the Sassi cave dwellings of Matera?",
    correctAnswer: "Italy",
    distractors: ["Greece", "Malta", "Croatia"],
    explanation: "The Sassi cave dwellings are in Matera, Italy.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "easy",
    question: "Which country is home to Machu Picchu?",
    correctAnswer: "Peru",
    distractors: ["Bolivia", "Ecuador", "Chile"],
    explanation: "Machu Picchu is an Inca site in Peru.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "intermediate",
    question: "Which African country contains the Okavango Delta?",
    correctAnswer: "Botswana",
    distractors: ["Namibia", "Zambia", "Zimbabwe"],
    explanation: "The Okavango Delta lies in northern Botswana.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "intermediate",
    question: "Which island group is part of Ecuador and inspired Darwin's voyage notes?",
    correctAnswer: "Galapagos Islands",
    distractors: ["Falkland Islands", "Canary Islands", "Azores"],
    explanation: "The Galapagos Islands are part of Ecuador and were important to Darwin's observations.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "intermediate",
    question: "Which sea is bordered by Jordan, Israel, and the West Bank?",
    correctAnswer: "Dead Sea",
    distractors: ["Red Sea", "Sea of Galilee", "Mediterranean Sea"],
    explanation: "The Dead Sea lies along Jordan, Israel, and the West Bank.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "hard",
    question: "Which country contains the UNESCO-listed city of Timbuktu?",
    correctAnswer: "Mali",
    distractors: ["Niger", "Chad", "Mauritania"],
    explanation: "Timbuktu is a historic city in Mali.",
    sourceKey: "geography_places",
  },
  {
    category: "geography",
    difficulty: "hard",
    question: "Which archipelago belongs to Yemen and is famous for dragon's blood trees?",
    correctAnswer: "Socotra",
    distractors: ["Comoros", "Seychelles", "Zanzibar"],
    explanation: "Socotra is a Yemeni archipelago known for unusual endemic plants.",
    sourceKey: "geography_places",
  },
  {
    category: "history",
    difficulty: "easy",
    question: "Which event happened first?",
    correctAnswer: "Magna Carta sealed",
    distractors: ["Fall of Constantinople", "Columbus reaches the Americas", "U.S. Declaration of Independence"],
    explanation: "Magna Carta was sealed in 1215, earlier than the other listed events.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "easy",
    question: "Which empire built much of the road network centered on Rome?",
    correctAnswer: "Roman Empire",
    distractors: ["Byzantine Empire", "Ottoman Empire", "Mongol Empire"],
    explanation: "Roman roads connected the Roman Empire's provinces to its centers of power.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "intermediate",
    question: "Which treaty divided newly encountered Atlantic territories between Spain and Portugal in 1494?",
    correctAnswer: "Treaty of Tordesillas",
    distractors: ["Treaty of Utrecht", "Treaty of Versailles", "Treaty of Paris"],
    explanation: "The Treaty of Tordesillas set a dividing line for Spanish and Portuguese claims.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "intermediate",
    question: "The storming of the Bastille is associated with which revolution?",
    correctAnswer: "French Revolution",
    distractors: ["Russian Revolution", "Haitian Revolution", "Mexican Revolution"],
    explanation: "The storming of the Bastille is a key early event of the French Revolution.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "intermediate",
    question: "Which happened before the others?",
    correctAnswer: "Printing press spreads in Europe",
    distractors: ["First modern Olympics", "Sputnik 1 launched", "Berlin Wall falls"],
    explanation: "Movable-type printing spread in Europe in the 15th century, centuries before the other events.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "hard",
    question: "Which ruler is associated with the 1868 Meiji Restoration?",
    correctAnswer: "Emperor Meiji",
    distractors: ["Emperor Taisho", "Emperor Hirohito", "Tokugawa Ieyasu"],
    explanation: "The Meiji Restoration restored imperial rule under Emperor Meiji.",
    sourceKey: "history_inventions",
  },
  {
    category: "history",
    difficulty: "hard",
    question: "Which Bronze Age writing system was deciphered by Michael Ventris?",
    correctAnswer: "Linear B",
    distractors: ["Linear A", "Cuneiform", "Meroitic script"],
    explanation: "Michael Ventris deciphered Linear B in the early 1950s.",
    sourceKey: "history_inventions",
  },
  {
    category: "inventions",
    difficulty: "easy",
    question: "Which invention is credited to Louis Braille?",
    correctAnswer: "Braille reading system",
    distractors: ["Morse code", "Semaphore flags", "Dvorak keyboard"],
    explanation: "Louis Braille developed the tactile reading and writing system named for him.",
    sourceKey: "history_inventions",
  },
  {
    category: "inventions",
    difficulty: "easy",
    question: "Which invention made grocery scanning possible after its 1970s retail rollout?",
    correctAnswer: "Barcode",
    distractors: ["Magstripe card", "Laser printer", "Fax machine"],
    explanation: "Barcodes enabled machine-readable product scanning in retail.",
    sourceKey: "history_inventions",
  },
  {
    category: "inventions",
    difficulty: "intermediate",
    question: "Which material fastener was inspired by burrs sticking to clothing and dog fur?",
    correctAnswer: "Velcro",
    distractors: ["Nylon zipper", "Safety pin", "Snap fastener"],
    explanation: "George de Mestral developed Velcro after studying hooked burrs.",
    sourceKey: "history_inventions",
  },
  {
    category: "inventions",
    difficulty: "intermediate",
    question: "Which invention did Tim Berners-Lee propose at CERN in 1989?",
    correctAnswer: "World Wide Web",
    distractors: ["Email", "Ethernet", "Linux kernel"],
    explanation: "Tim Berners-Lee proposed the World Wide Web while working at CERN.",
    sourceKey: "history_inventions",
  },
  {
    category: "inventions",
    difficulty: "intermediate",
    question: "Which device did Alexander Graham Bell patent in 1876?",
    correctAnswer: "Telephone",
    distractors: ["Telegraph", "Phonograph", "Radio"],
    explanation: "Bell received a U.S. patent for the telephone in 1876.",
    sourceKey: "history_inventions",
  },
  {
    category: "inventions",
    difficulty: "hard",
    question: "Which invention was patented by Laszlo Biro and made quick-drying ink practical for everyday writing?",
    correctAnswer: "Ballpoint pen",
    distractors: ["Fountain pen", "Mechanical pencil", "Felt-tip marker"],
    explanation: "Laszlo Biro's ballpoint pen used a tiny rolling ball and quick-drying ink.",
    sourceKey: "history_inventions",
  },
  {
    category: "inventions",
    difficulty: "hard",
    question: "Which creation came first?",
    correctAnswer: "Phonograph",
    distractors: ["Compact disc", "QR code", "World Wide Web"],
    explanation: "Edison's phonograph dates to 1877, long before the other listed technologies.",
    sourceKey: "history_inventions",
  },
  {
    category: "language",
    difficulty: "easy",
    question: "Which language uses the Hangul writing system?",
    correctAnswer: "Korean",
    distractors: ["Japanese", "Vietnamese", "Thai"],
    explanation: "Hangul is the alphabetic writing system used for Korean.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "language",
    difficulty: "easy",
    question: "Which language is written with the Greek alphabet?",
    correctAnswer: "Greek",
    distractors: ["Armenian", "Georgian", "Hebrew"],
    explanation: "Modern Greek is written with the Greek alphabet.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "language",
    difficulty: "intermediate",
    question: "Which language is usually classified as a Uralic language?",
    correctAnswer: "Finnish",
    distractors: ["Swedish", "Polish", "Latvian"],
    explanation: "Finnish belongs to the Uralic language family.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "language",
    difficulty: "intermediate",
    question: "Which language is a Bantu language widely used as a lingua franca in East Africa?",
    correctAnswer: "Swahili",
    distractors: ["Amharic", "Somali", "Hausa"],
    explanation: "Swahili is a Bantu language used across much of East Africa.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "language",
    difficulty: "intermediate",
    question: "Which writing system was created in the 19th century by Sequoyah?",
    correctAnswer: "Cherokee syllabary",
    distractors: ["Cree syllabics", "Vai syllabary", "N'Ko script"],
    explanation: "Sequoyah created the Cherokee syllabary for the Cherokee language.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "language",
    difficulty: "hard",
    question: "Which language isolate is spoken in the Basque Country?",
    correctAnswer: "Basque",
    distractors: ["Catalan", "Occitan", "Galician"],
    explanation: "Basque is a language isolate, unrelated to neighboring Romance languages.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "language",
    difficulty: "hard",
    question: "Which constructed language was published by L. L. Zamenhof in 1887?",
    correctAnswer: "Esperanto",
    distractors: ["Interlingua", "Volapuk", "Ido"],
    explanation: "Zamenhof published Esperanto in 1887 under the name Dr. Esperanto.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "literature_arts",
    difficulty: "easy",
    question: "Which artist painted Guernica?",
    correctAnswer: "Pablo Picasso",
    distractors: ["Salvador Dali", "Joan Miro", "Diego Rivera"],
    explanation: "Pablo Picasso painted Guernica in response to the bombing of the Basque town.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "literature_arts",
    difficulty: "easy",
    question: "Which novel opens with the Bennet family and questions of marriage and inheritance?",
    correctAnswer: "Pride and Prejudice",
    distractors: ["Charlotte Bronte's Jane Eyre", "Emily Bronte's Wuthering Heights", "George Eliot's Middlemarch"],
    explanation: "Jane Austen's Pride and Prejudice centers on the Bennet family.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "literature_arts",
    difficulty: "intermediate",
    question: "Which Japanese woodblock print shows a towering wave near Mount Fuji?",
    correctAnswer: "The Great Wave off Kanagawa",
    distractors: ["Sudden Shower over Shin-Ohashi", "Red Fuji", "Plum Estate in Kameido"],
    explanation: "Hokusai's The Great Wave off Kanagawa depicts a huge wave with Mount Fuji in the distance.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "literature_arts",
    difficulty: "intermediate",
    question: "Which Nigerian novel by Chinua Achebe begins with the wrestler Okonkwo?",
    correctAnswer: "Things Fall Apart",
    distractors: ["Arrow of God", "No Longer at Ease", "The River Between"],
    explanation: "Things Fall Apart introduces Okonkwo and Igbo society before colonial disruption.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "literature_arts",
    difficulty: "intermediate",
    question: "Which composer wrote the Four Seasons violin concertos?",
    correctAnswer: "Antonio Vivaldi",
    distractors: ["Johann Sebastian Bach", "George Frideric Handel", "Domenico Scarlatti"],
    explanation: "Antonio Vivaldi composed the concertos known as The Four Seasons.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "literature_arts",
    difficulty: "hard",
    question: "Which modernist novel takes place on a single day in Dublin, June 16, 1904?",
    correctAnswer: "Ulysses",
    distractors: ["Mrs Dalloway", "The Trial", "Nightwood"],
    explanation: "James Joyce's Ulysses follows one day in Dublin on June 16, 1904.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "literature_arts",
    difficulty: "hard",
    question: "Which medieval work is often called the first major work of Italian literature?",
    correctAnswer: "Dante's Divine Comedy",
    distractors: ["Boccaccio's Decameron", "Song of Roland", "Chaucer's Canterbury Tales"],
    explanation: "Dante's Divine Comedy is a landmark of Italian literature.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "culture",
    difficulty: "easy",
    question: "Which country is strongly associated with the flamenco tradition?",
    correctAnswer: "Spain",
    distractors: ["Portugal", "Italy", "Greece"],
    explanation: "Flamenco developed in southern Spain, especially Andalusia.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "culture",
    difficulty: "easy",
    question: "Which country is the birthplace of kabuki theatre?",
    correctAnswer: "Japan",
    distractors: ["China", "Korea", "Thailand"],
    explanation: "Kabuki originated in Japan in the early modern period.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "culture",
    difficulty: "intermediate",
    question: "Which dance is historically linked with Buenos Aires and Montevideo?",
    correctAnswer: "Tango",
    distractors: ["Samba", "Waltz", "Flamenco"],
    explanation: "Tango developed around the Rio de la Plata cities of Buenos Aires and Montevideo.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "culture",
    difficulty: "intermediate",
    question: "Which UNESCO-listed festival is famous for giant papier-mache figures burned in Valencia?",
    correctAnswer: "Las Fallas",
    distractors: ["La Tomatina", "San Fermin", "Feria de Abril"],
    explanation: "Las Fallas in Valencia features large figures that are set alight during the festival.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "culture",
    difficulty: "intermediate",
    question: "Which board game uses black and white stones on a grid and is called weiqi in Chinese?",
    correctAnswer: "Go",
    distractors: ["Shogi", "Xiangqi", "Mahjong"],
    explanation: "Go is known as weiqi in Chinese and uses black and white stones on a grid.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "culture",
    difficulty: "hard",
    question: "Which textile-resist dyeing technique is closely associated with Indonesia?",
    correctAnswer: "Batik",
    distractors: ["Ikat", "Brocade", "Tartan"],
    explanation: "Indonesian batik is a well-known wax-resist dyeing tradition.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "culture",
    difficulty: "hard",
    question: "Which tea ceremony is known in Japanese as chanoyu?",
    correctAnswer: "Japanese tea ceremony",
    distractors: ["Chinese gongfu tea", "Korean darye", "Moroccan mint tea"],
    explanation: "Chanoyu refers to the Japanese tea ceremony.",
    sourceKey: "language_arts_culture",
  },
  {
    category: "fun_facts",
    difficulty: "easy",
    question: "Which fruit floats in water because it contains air pockets?",
    correctAnswer: "Apple",
    distractors: ["Grape", "Mango", "Fig"],
    explanation: "Apples can float because their flesh contains enough trapped air to lower their density.",
    sourceKey: "science_constants_space",
  },
  {
    category: "fun_facts",
    difficulty: "easy",
    question: "Which animal's fingerprints can be so similar to humans that they can confuse crime scenes?",
    correctAnswer: "Koala",
    distractors: ["Panda", "Sloth", "Lemur"],
    explanation: "Koalas have fingerprints that can look strikingly human-like.",
    sourceKey: "science_constants_space",
  },
  {
    category: "fun_facts",
    difficulty: "intermediate",
    question: "Which plant can close its leaflets rapidly when touched?",
    correctAnswer: "Mimosa pudica",
    distractors: ["Venus flytrap", "Pitcher plant", "Rafflesia"],
    explanation: "Mimosa pudica is known for touch-sensitive leaf movement.",
    sourceKey: "science_constants_space",
  },
  {
    category: "fun_facts",
    difficulty: "intermediate",
    question: "Which bird can mimic chainsaws, camera shutters, and other complex sounds?",
    correctAnswer: "Lyrebird",
    distractors: ["Toucan", "Puffin", "Kingfisher"],
    explanation: "Lyrebirds are famous for elaborate mimicry of natural and artificial sounds.",
    sourceKey: "science_constants_space",
  },
  {
    category: "fun_facts",
    difficulty: "intermediate",
    question: "Which animal can change color using specialized skin cells called chromatophores?",
    correctAnswer: "Cuttlefish",
    distractors: ["Jellyfish", "Sea sponge", "Clownfish"],
    explanation: "Cuttlefish use chromatophores and other skin structures for rapid color change.",
    sourceKey: "science_constants_space",
  },
  {
    category: "fun_facts",
    difficulty: "hard",
    question: "Which mammal is the other living monotreme group besides the platypus?",
    correctAnswer: "Echidna",
    distractors: ["Quokka", "Bilby", "Numbat"],
    explanation: "Echidnas and platypuses are the living monotreme mammals.",
    sourceKey: "science_constants_space",
  },
  {
    category: "fun_facts",
    difficulty: "hard",
    question: "Which marine animal has blue blood because it uses hemocyanin to carry oxygen?",
    correctAnswer: "Horseshoe crab",
    distractors: ["Hermit crab", "Sea turtle", "Manta ray"],
    explanation: "Horseshoe crab blood contains copper-based hemocyanin, giving it a blue color.",
    sourceKey: "science_constants_space",
  },
];

export const knowledgeExpansionV1Questions = buildRows(RAW_EXPANSION_FACTS);
export const questions = knowledgeExpansionV1Questions;
export default knowledgeExpansionV1Questions;
