/**
 * SEO contract — the indexable surface's rules, enforced on what actually
 * ships: the static layer generated by seo/build.mjs (homepage, /games/, the
 * quiz archive, grid answers, career path quizzes, sitemap, app shell).
 *
 * The generator runs once here against a stub of the built shell, from the
 * committed archive snapshot (no network). Every assertion below was a
 * production failure mode or a hand-check that would silently rot: titles past
 * the SERP budget, duplicate titles across hundreds of generated pages, a page
 * missing from the sitemap, a canonical on the www host, a Play button pointing
 * at a route the app doesn't have, the app shell becoming indexable.
 */
import { describe, it, expect, beforeAll } from "vitest";
import { mkdtempSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { generate } from "../../seo/build.mjs";
import {
  ROUTE_META,
  DEFAULT_META,
  TITLE_MAX,
  DESCRIPTION_MAX,
  resolveRouteMeta,
  canonicalFor,
  CANONICAL_OVERRIDES,
} from "@/lib/routeMeta";

const read = (p: string) => readFileSync(p, "utf8");

let dist = "";
let pages: string[] = [];
const html = (pagePath: string) => read(path.join(dist, pagePath, "index.html"));

beforeAll(async () => {
  dist = mkdtempSync(path.join(tmpdir(), "vq-seo-"));
  // The built shell differs from the source only in its hashed asset tags,
  // which the generator carries through untouched.
  const shell = read("index.html").replace(
    '<script type="module" src="/src/main.tsx"></script>',
    '<script type="module" crossorigin src="/assets/index-test.js"></script>\n    <link rel="stylesheet" crossorigin href="/assets/index-test.css">',
  );
  writeFileSync(path.join(dist, "index.html"), shell);
  const prev = process.env.VITE_CONVEX_URL;
  delete process.env.VITE_CONVEX_URL; // snapshot only — never the network in tests
  const result = await generate({ distDir: dist, log: () => {} });
  if (prev !== undefined) process.env.VITE_CONVEX_URL = prev;
  pages = result.pages.map((p) => p.path);
}, 60_000);

const pick = (h: string, re: RegExp) => h.match(re)?.[1]?.trim() ?? null;
const decode = (s: string) =>
  s.replace(/&amp;/g, "&").replace(/&quot;/g, '"').replace(/&lt;/g, "<").replace(/&gt;/g, ">");
const title = (h: string) => {
  const t = pick(h, /<title>(.*?)<\/title>/s);
  return t === null ? null : decode(t);
};
const description = (h: string) => {
  const d = pick(h, /<meta name="description" content="(.*?)"/s);
  return d === null ? null : decode(d);
};
const canonical = (h: string) => pick(h, /<link rel="canonical" href="(.*?)"/s);

describe("generated static surface", () => {
  it("covers every section with a real number of pages", () => {
    expect(pages).toContain("/");
    expect(pages).toContain("/games/");
    expect(pages.filter((p) => p.startsWith("/games/")).length).toBeGreaterThanOrEqual(8);
    expect(pages.filter((p) => /^\/football-quiz\/\d{4}-\d{2}-\d{2}\/$/.test(p)).length).toBeGreaterThan(100);
    expect(pages.filter((p) => p.startsWith("/who-played-for/")).length).toBeGreaterThan(300);
    expect(pages.filter((p) => p.startsWith("/career-path-quiz/")).length).toBeGreaterThan(30);
  });

  it("keeps every title and description within the SERP budget", () => {
    for (const p of pages) {
      const h = html(p);
      const t = title(h);
      const d = description(h);
      expect(t, `${p} has no <title>`).toBeTruthy();
      expect(t!.length, `${p} title (${t!.length}): ${t}`).toBeLessThanOrEqual(TITLE_MAX);
      expect(d, `${p} has no description`).toBeTruthy();
      expect(d!.length, `${p} description is ${d!.length} chars`).toBeLessThanOrEqual(DESCRIPTION_MAX);
    }
  });

  it("gives every page a unique title and description", () => {
    const titles = pages.map((p) => title(html(p)));
    const descs = pages.map((p) => description(html(p)));
    expect(new Set(titles).size).toBe(titles.length);
    expect(new Set(descs).size).toBe(descs.length);
  });

  it("self-references a non-www canonical on every page", () => {
    for (const p of pages) {
      expect(canonical(html(p)), p).toBe(`https://verveq.com${p}`);
    }
  });

  it("has exactly one h1 on every page but the homepage (whose h1 is the landing's)", () => {
    for (const p of pages.filter((x) => x !== "/")) {
      expect((html(p).match(/<h1[\s>]/g) ?? []).length, p).toBe(1);
    }
    expect((html("/").match(/<h1[\s>]/g) ?? []).length).toBe(0);
    expect((read("src/pages/shell/ColdEntryScreen.tsx").match(/<h1[\s>]/g) ?? []).length).toBe(1);
  });

  it("ships only valid JSON-LD", () => {
    for (const p of pages) {
      for (const m of html(p).matchAll(/<script type="application\/ld\+json">(.*?)<\/script>/gs)) {
        expect(() => JSON.parse(m[1]), p).not.toThrow();
      }
    }
  });

  it("never references the www host", () => {
    for (const p of pages) expect(html(p), p).not.toContain("www.verveq.com");
  });

  it("keeps the app bundle on every page so Play needs no page load", () => {
    for (const p of pages) expect(html(p), p).toContain('src="/assets/index-test.js"');
  });

  it("points every Play button at a route the app actually has", () => {
    const app = read("src/App.tsx");
    for (const p of pages) {
      for (const m of html(p).matchAll(/class="seo-cta[^"]*" data-spa href="([^"?]+)/g)) {
        expect(app, `${p} → ${m[1]}`).toContain(`path="${m[1]}"`);
      }
    }
  });

  it("never publishes today's daily quiz", () => {
    const today = new Date().toISOString().slice(0, 10);
    expect(pages).not.toContain(`/football-quiz/${today}/`);
  });
});

describe("app shell", () => {
  it("is noindex and carries no canonical", () => {
    const shell = read(path.join(dist, "app-shell.html"));
    expect(shell).toContain('<meta name="robots" content="noindex, follow" />');
    expect(canonical(shell)).toBeNull();
    expect(shell).not.toContain('id="seo"');
  });
});

describe("sitemap ↔ generated pages", () => {
  let locs: string[] = [];
  beforeAll(() => {
    locs = [...read(path.join(dist, "sitemap.xml")).matchAll(/<loc>(.*?)<\/loc>/g)].map((m) => m[1]);
  });

  it("lists only non-www, absolute URLs", () => {
    for (const loc of locs) expect(loc.startsWith("https://verveq.com/"), loc).toBe(true);
  });

  it("lists every generated page and the legal pages, and nothing dead", () => {
    const paths = new Set(locs.map((l) => new URL(l).pathname));
    for (const p of pages) expect(paths.has(p), `${p} missing from sitemap`).toBe(true);
    expect(paths.has("/privacy")).toBe(true);
    expect(paths.has("/terms")).toBe(true);
    for (const p of paths) {
      if (p === "/privacy" || p === "/terms") {
        expect(existsSync(`public${p}/index.html`), p).toBe(true);
        continue;
      }
      expect(pages, `${p} in sitemap but not generated`).toContain(p);
    }
  });
});

describe("canonical host consolidation", () => {
  it("nginx 301s the www host to the apex, preserving path and query", () => {
    const conf = read("../deploy/nginx.conf");
    expect(conf).toContain("server_name www.verveq.com;");
    expect(conf).toContain("return 301 https://verveq.com$request_uri;");
  });

  it("nginx answers unknown paths with a real 404 and redirects relatively", () => {
    const conf = read("../deploy/nginx.conf");
    expect(conf).toContain("absolute_redirect off;");
    expect(conf).toMatch(/location @spa\s*{[\s\S]*?return 404;/);
    expect(conf).toMatch(/rewrite \^ \/app-shell\.html last;/);
  });
});

describe("SPA route metadata", () => {
  it("keeps every title and description within the SERP budget", () => {
    for (const [p, meta] of Object.entries(ROUTE_META)) {
      expect(meta.title.length, `${p}: ${meta.title}`).toBeLessThanOrEqual(TITLE_MAX);
      expect(meta.description.length, `${p} description`).toBeLessThanOrEqual(DESCRIPTION_MAX);
    }
  });

  it("gives every route a distinct title", () => {
    const titles = Object.values(ROUTE_META).map((m) => m.title);
    expect(new Set(titles).size).toBe(titles.length);
  });

  it("falls back to the homepage's own head values", () => {
    const home = html("/");
    expect(DEFAULT_META.title).toBe(title(home));
    expect(DEFAULT_META.description).toBe(description(home));
    expect(resolveRouteMeta("/does-not-exist")).toEqual(DEFAULT_META);
  });

  it("normalises a trailing slash", () => {
    expect(resolveRouteMeta("/compete/")).toEqual(ROUTE_META["/compete"]);
    expect(canonicalFor("/compete/")).toBe("https://verveq.com/compete");
  });

  it("builds non-www canonicals, deferring game routes to their static page", () => {
    expect(canonicalFor("/")).toBe("https://verveq.com/");
    expect(canonicalFor("/compete")).toBe("https://verveq.com/compete");
    expect(canonicalFor("/v2/daily")).toBe("https://verveq.com/games/daily-football-quiz/");
    for (const target of Object.values(CANONICAL_OVERRIDES)) {
      expect(pages, `${target} is not a generated page`).toContain(target);
    }
  });
});
