import React from "react";
import { AbsoluteFill, Audio, Sequence, staticFile } from "remotion";
import { COLORS } from "./kit";
import { SCENES, START } from "./timeline";
import { SCENE_COMPONENTS } from "./scenes";

// The hero marketing promo: a scored, scene-sequenced hype reel. Unlike the
// daily quiz clips, this bakes its own soundtrack (public/promo/soundtrack.wav,
// generated by promo/audio-gen.mjs) because it IS the ad — every visual hit is
// arranged to land on the track's beats.
export const BrandPromo: React.FC = () => (
  <AbsoluteFill style={{ background: COLORS.cream }}>
    <Audio src={staticFile("promo/soundtrack.wav")} />
    {SCENES.map((s) => {
      const Comp = SCENE_COMPONENTS[s.key];
      return (
        <Sequence key={s.key} from={START[s.key]} durationInFrames={s.dur} layout="none">
          <Comp dur={s.dur} />
        </Sequence>
      );
    })}
  </AbsoluteFill>
);
