import { internalMutation } from "../_generated/server";
import { v } from "convex/values";

// One-shot operator migration. Finds every Password-provider auth account
// whose email ends in "@verveq.local" (the pre-BLOCKER-1 pattern where
// password was a deterministic transform of the display name) and
// invalidates it — deletes the associated authAccounts, authSessions,
// authRefreshTokens, authVerificationCodes, and authVerifiers rows so the
// compromised credentials cannot be used to sign in again.
//
// The users doc is intentionally left in place so stats, ELO history, and
// game sessions are preserved. The username is cleared if it matches the
// legacy deterministic pattern (local part of the fake email) so a new
// signup with the same address can pick a fresh username.
//
// Run once from the Convex dashboard after the BLOCKER-1 fix deploys:
//     npx convex run migrations/invalidateLegacyAuth:run '{"dryRun": false}'
//
// Pass {"dryRun": true} first to see the counts without writing.

export const run = internalMutation({
  args: {
    dryRun: v.optional(v.boolean()),
  },
  handler: async (ctx, { dryRun }) => {
    const isDryRun = dryRun === true;

    const allUsers = await ctx.db.query("users").collect();
    const legacyUsers = allUsers.filter((u) => {
      const email = typeof u.email === "string" ? u.email.toLowerCase() : "";
      return email.endsWith("@verveq.local");
    });

    let invalidatedAccounts = 0;
    let invalidatedSessions = 0;
    let invalidatedRefreshTokens = 0;
    let invalidatedVerificationCodes = 0;
    let invalidatedVerifiers = 0;
    let clearedUsernames = 0;
    let touchedUserDocs = 0;

    for (const user of legacyUsers) {
      const userId = user._id;

      const accounts = await ctx.db
        .query("authAccounts")
        .withIndex("userIdAndProvider", (q) => q.eq("userId", userId))
        .collect();

      for (const account of accounts) {
        const codes = await ctx.db
          .query("authVerificationCodes")
          .withIndex("accountId", (q) => q.eq("accountId", account._id))
          .collect();
        for (const code of codes) {
          if (!isDryRun) await ctx.db.delete(code._id);
          invalidatedVerificationCodes++;
        }
        if (!isDryRun) await ctx.db.delete(account._id);
        invalidatedAccounts++;
      }

      const sessions = await ctx.db
        .query("authSessions")
        .withIndex("userId", (q) => q.eq("userId", userId))
        .collect();

      for (const session of sessions) {
        const refreshTokens = await ctx.db
          .query("authRefreshTokens")
          .withIndex("sessionId", (q) => q.eq("sessionId", session._id))
          .collect();
        for (const token of refreshTokens) {
          if (!isDryRun) await ctx.db.delete(token._id);
          invalidatedRefreshTokens++;
        }
        const verifiers = await ctx.db
          .query("authVerifiers")
          .collect()
          .then((rows) => rows.filter((r) => r.sessionId === session._id));
        for (const verifier of verifiers) {
          if (!isDryRun) await ctx.db.delete(verifier._id);
          invalidatedVerifiers++;
        }
        if (!isDryRun) await ctx.db.delete(session._id);
        invalidatedSessions++;
      }

      // Clear the username if it matches the legacy autogenerated pattern
      // (the email's local part), and clear the legacy email so the
      // existing users doc doesn't conflict with a future signup using the
      // same real address.
      const localPart = (user.email ?? "").toLowerCase().split("@")[0] ?? "";
      const usernameMatchesLocal =
        typeof user.username === "string" &&
        user.username.toLowerCase() === localPart &&
        localPart.length > 0;

      if (usernameMatchesLocal) clearedUsernames++;
      if (!isDryRun) {
        await ctx.db.patch(userId, {
          email: undefined,
          emailVerificationTime: undefined,
          isGuest: false,
          ...(usernameMatchesLocal ? { username: undefined } : {}),
        });
      }
      touchedUserDocs++;
    }

    const summary = {
      dryRun: isDryRun,
      legacyUserCount: legacyUsers.length,
      invalidatedAccounts,
      invalidatedSessions,
      invalidatedRefreshTokens,
      invalidatedVerificationCodes,
      invalidatedVerifiers,
      clearedUsernames,
      touchedUserDocs,
    };

    console.log("[invalidateLegacyAuth]", JSON.stringify(summary));
    return summary;
  },
});
