// TIER LIST — fact gate. One board, eight Premier League strikers, S/A/B/C.
// The tiers are OPINION (that is the format: "wrong? fix it"). Everything
// else on screen is a fact and is double-sourced at least (lab/tests-wiki.mjs),
// failing loudly on any disagreement:
//
//   name + club chip  the player played for that club (senior team):
//                     football_career_paths.json AND Wikidata P54 AND the
//                     Wikipedia infobox senior clubs (link → club QID)
//   "PREMIER LEAGUE"  that spell reaches the Premier League era (1992–93 on)
//                     in BOTH Wikidata P580/P582 and the infobox yearsN
//   "STRIKERS"        Wikidata P413 AND the infobox `position =` both say
//                     forward / striker / centre-forward
//
//   node lab/tierlist-facts.mjs           # resolve what is missing, gate, write
//   node lab/tierlist-facts.mjs --check   # offline: gate from cache, assert facts.json
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { CHECK, CLUBS, assertClubs, dataClubs, fmtWd, gateReport, isFootballer, resolveInfobox, resolvePlayer, span, wdSenior, wpSenior } from "./tests-wiki.mjs";

const dir = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(dir, "..", "src", "lab", "tierlist", "facts.json");

export const TITLE = ["PREMIER LEAGUE", "STRIKERS"];
// tier order is the board; within a tier, left → right
export const TIERS = [
  { tier: "S", players: [["Thierry Henry", "HENRY", "arsenal"], ["Alan Shearer", "SHEARER", "newcastle"], ["Sergio Agüero", "AGÜERO", "mancity"]] },
  { tier: "A", players: [["Harry Kane", "KANE", "tottenham"], ["Didier Drogba", "DROGBA", "chelsea"]] },
  { tier: "B", players: [["Erling Haaland", "HAALAND", "mancity"], ["Luis Suárez", "SUÁREZ", "liverpool"]] },
  { tier: "C", players: [["Wayne Rooney", "ROONEY", "manutd"]] },
];
const PL_FIRST = 1993; // the 1992–93 season ends in 1993: a spell must reach it
const STRIKER = /forward|striker/i;
const SEARCH = {};

const main = async () => {
  const problems = [];
  const fail = (m) => problems.push(m);
  const all = TIERS.flatMap((t) => t.players);
  if (all.length !== 8 || new Set(all.map((p) => p[0])).size !== 8) fail("eight distinct players");
  problems.push(...(await assertClubs([...new Set(all.map((p) => p[2]))])));

  const tiers = [];
  for (const t of TIERS) {
    const players = [];
    for (const [name, show, key] of t.players) {
      const club = CLUBS[key];
      const P = await resolvePlayer(name, SEARCH[name]);
      const IB = await resolveInfobox(P);
      if (!isFootballer(P)) fail(`${name}: Wikidata ${P.qid} is "${P.description}"`);
      const dc = dataClubs(name);
      const d = (dc ?? []).filter((c) => c.name === club.data);
      const w = wdSenior(P, club);
      const wp = wpSenior(IB, club);
      if (!dc) fail(`${name}: not exactly one career-paths entry`);
      else if (!d.length) fail(`${name}: career data has no "${club.data}"`);
      if (!w.length) fail(`${name}: Wikidata ${P.qid} P54 lacks senior ${club.show}`);
      if (!wp.length) fail(`${name}: Wikipedia "${IB.title}" infobox lists no senior ${club.show}`);
      // Premier League era, both sources
      const wdPL = w.filter((s) => Number(s.end ?? 9999) >= PL_FIRST);
      const wpPL = wp.filter((c) => (span(c.years)?.to ?? 0) >= PL_FIRST);
      if (w.length && !wdPL.length) fail(`${name}: Wikidata ${club.show} spell ends before the Premier League (${w.map(fmtWd)})`);
      if (w.some((s) => !s.start)) fail(`${name}: Wikidata ${club.show} spell has no start date`);
      if (wp.length && !wpPL.length) fail(`${name}: Wikipedia ${club.show} years ${wp.map((c) => c.years)} end before the Premier League`);
      // striker, both sources
      const wdPos = P.positions.filter((l) => STRIKER.test(l));
      const wpPos = STRIKER.test(IB.position);
      if (!wdPos.length) fail(`${name}: Wikidata P413 ${JSON.stringify(P.positions)} has no forward/striker`);
      if (!wpPos) fail(`${name}: Wikipedia infobox position "${IB.position}" is not forward/striker`);
      console.log(`${t.tier}  ${name.padEnd(15)} ${club.show.padEnd(11)} data ${d.length ? "✓" : "✗"} · wikidata ${w.map(fmtWd).join("; ") || "✗"} · wikipedia ${wp.map((c) => `${c.years} ${c.target}`).join("; ") || "✗"}`);
      console.log(`                   position: wikidata ${JSON.stringify(P.positions)} · wikipedia "${IB.position}"`);
      players.push({ name, show, club: { key, show: club.show, bg: club.bg, fg: club.fg, qid: club.qid }, qid: P.qid, wikipedia: IB.ref, years: { wikidata: w.map((s) => `${s.start ?? "?"}–${s.end ?? ""}`), wikipedia: wp.map((c) => c.years) } });
    }
    tiers.push({ tier: t.tier, players });
  }
  gateReport("TIER LIST", problems);
  const facts = {
    _doc: "Generated by lab/tierlist-facts.mjs — names, clubs, PL era and position double/triple-sourced (career paths + Wikidata + Wikipedia infobox). Tier placement is editorial opinion. Do not edit; re-run the script.",
    title: TITLE,
    tiers,
  };
  if (CHECK) {
    const cur = JSON.parse(readFileSync(OUT, "utf8"));
    if (JSON.stringify(cur.tiers) !== JSON.stringify(tiers)) {
      console.error("✗ --check: facts.json drifted from the gate — re-run without --check");
      process.exit(1);
    }
    console.log("\n✓ TIER LIST GATE PASSED (offline) — 8 strikers, every club chip triple-sourced.");
    return;
  }
  writeFileSync(OUT, JSON.stringify(facts, null, 1));
  console.log(`\n✓ TIER LIST GATE PASSED — 8 strikers, every club chip triple-sourced.\n→ ${OUT}`);
};
main().catch((e) => {
  console.error(e);
  process.exit(1);
});
