// THE XI — fact gate. Eleven names on a pitch, one club they all played for.
// Club membership is asserted against football_career_paths.json for every
// name, AND the script proves the connecting club is UNIQUE (no second club
// shared by all eleven), so "one club connects them all" is a true sentence.
// Positions come from THE DRAW's Wikidata-sourced cards where a card exists;
// the formation slot is editorial.
//
//   node lab/xi-facts.mjs
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const dir = path.dirname(fileURLToPath(import.meta.url));
const DATA = path.join(dir, "..", "..", "..", "app", "convex", "data");
const OUT = path.join(dir, "..", "src", "lab", "xi", "facts.json");
const paths = JSON.parse(readFileSync(path.join(DATA, "football_career_paths.json"), "utf8"));
const cards = JSON.parse(readFileSync(path.join(DATA, "drawCardsReal.candidates.json"), "utf8"));
const meta = JSON.parse(readFileSync(path.join(DATA, "football_player_metadata.json"), "utf8"));
const byName = new Map(paths.map((p) => [p.answerName, p]));
const cardOf = new Map(cards.map((c) => [c.name, c]));
const clubName = (c) => (typeof c === "string" ? c : c.name);

export const CLUB = "Inter Milan";
export const CLUB_SHOW = "INTER MILAN";
// reveal order = the order the plates land: the connections people FORGET
// first, the giveaway last. slot = formation position key (4-3-3).
export const XI = [
  { name: "Dennis Bergkamp", show: "BERGKAMP", slot: "LW" },
  { name: "Roberto Carlos", show: "ROBERTO CARLOS", slot: "LB" },
  { name: "Andrea Pirlo", show: "PIRLO", slot: "CM1" },
  { name: "Clarence Seedorf", show: "SEEDORF", slot: "CM2" },
  { name: "Philippe Coutinho", show: "COUTINHO", slot: "RW" },
  { name: "André Onana", show: "ONANA", slot: "GK" },
  { name: "Achraf Hakimi", show: "HAKIMI", slot: "RB" },
  { name: "Maicon", show: "MAICON", slot: "CB1" },
  { name: "Wesley Sneijder", show: "SNEIJDER", slot: "CM3" },
  { name: "Ronaldo Nazário", show: "RONALDO", slot: "ST" },
  { name: "Javier Zanetti", show: "ZANETTI", slot: "CB2" },
];
const SLOT_POS = { GK: "GK", LB: "DEF", CB1: "DEF", CB2: "DEF", RB: "DEF", CM1: "MID", CM2: "MID", CM3: "MID", LW: "ATT", ST: "ATT", RW: "ATT" };
const META_POS = { Goalkeeper: "GK", Defender: "DEF", Midfield: "MID", Attack: "ATT" };

const main = () => {
  if (XI.length !== 11) throw new Error("eleven names");
  if (new Set(XI.map((x) => x.slot)).size !== 11) throw new Error("eleven distinct slots");
  const clubSets = [];
  for (const x of XI) {
    const p = byName.get(x.name);
    if (!p) throw new Error(`"${x.name}" is not in football_career_paths.json`);
    const clubs = new Set(p.clubs.map(clubName));
    if (!clubs.has(CLUB)) throw new Error(`${x.name} never played for ${CLUB} on his dataset path: ${[...clubs].join(" > ")}`);
    clubSets.push(clubs);
    const want = SLOT_POS[x.slot];
    const card = cardOf.get(x.name);
    const m = meta[x.name];
    const have = card?.position ?? (m ? META_POS[m.position] : undefined);
    if (!have) throw new Error(`${x.name}: no position source (no DRAW card, no metadata)`);
    // Maicon: CB slot for a right-back is a formation liberty, position class DEF still matches
    if (have !== want) throw new Error(`${x.name}: sourced position ${have} but slot ${x.slot} wants ${want}`);
    x.position = have;
    x.positionSource = card ? "drawCardsReal (Wikidata)" : "football_player_metadata";
  }
  // uniqueness: the only club on all eleven paths is CLUB
  let common = new Set(clubSets[0]);
  for (const s of clubSets.slice(1)) common = new Set([...common].filter((c) => s.has(c)));
  if (common.size !== 1 || !common.has(CLUB)) throw new Error(`connecting club is not unique: ${[...common].join(", ")}`);
  const facts = {
    _doc: "Generated by lab/xi-facts.mjs from football_career_paths.json (+ DRAW cards / metadata for positions). Do not edit — re-run the script.",
    club: CLUB,
    clubShow: CLUB_SHOW,
    xi: XI.map((x, i) => ({ i, ...x })),
  };
  writeFileSync(OUT, JSON.stringify(facts, null, 1));
  for (const x of facts.xi) console.log(`${String(x.i + 1).padStart(2)}  ${x.show.padEnd(15)} ${x.slot.padEnd(4)} ${x.position}  (${x.positionSource})`);
  console.log(`all eleven carry ${CLUB}; no other club is shared by all eleven.\n→ ${OUT}`);
};
main();
